/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

//package lasso;

using System;
public class Assertion : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal Assertion(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected Assertion() : this(IntPtr.Zero, false) {
  }

  ~Assertion() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      lassoPINVOKE.delete_Assertion(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  internal static IntPtr getCPtr(Assertion obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  public Assertion(string issuer, string requestId) : this(lassoPINVOKE.new_Assertion(issuer, requestId), true) {
  }

  public string dump() {
    return lassoPINVOKE.Assertion_dump(swigCPtr);
  }

}
