//package lasso;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


using System;
using System.Runtime.InteropServices;

class lassoPINVOKE {

  class SWIGExceptionHelper {

    public delegate void SWIGExceptionDelegate(string message);

    static SWIGExceptionDelegate systemDelegate = new SWIGExceptionDelegate(ThrowSystemException);
    static SWIGExceptionDelegate outOfMemoryDelegate = new SWIGExceptionDelegate(ThrowOutOfMemoryException);
    static SWIGExceptionDelegate indexOutOfRangeDelegate = new SWIGExceptionDelegate(ThrowIndexOutOfRangeException);
    static SWIGExceptionDelegate divideByZeroDelegate = new SWIGExceptionDelegate(ThrowDivideByZeroException);
    static SWIGExceptionDelegate argumentOutOfRangeDelegate = new SWIGExceptionDelegate(ThrowArgumentOutOfRangeException);
    static SWIGExceptionDelegate nullReferenceDelegate = new SWIGExceptionDelegate(ThrowNullReferenceException);

    [DllImport("lasso", EntryPoint="SWIGRegisterExceptionCallbacks_lasso")]
    public static extern void SWIGRegisterExceptionCallbacks_lasso(
      SWIGExceptionDelegate systemExceptionDelegate,
      SWIGExceptionDelegate outOfMemoryDelegate, 
      SWIGExceptionDelegate indexOutOfRangeDelegate, 
      SWIGExceptionDelegate divideByZeroDelegate, 
      SWIGExceptionDelegate argumentOutOfRangeDelegate,
      SWIGExceptionDelegate nullReferenceDelegate);

    static void ThrowSystemException(string message) {
      throw new System.SystemException(message);
    }

    static void ThrowOutOfMemoryException(string message) {
      throw new System.OutOfMemoryException(message);
    }

    static void ThrowIndexOutOfRangeException(string message) {
      throw new System.IndexOutOfRangeException(message);
    }

    static void ThrowDivideByZeroException(string message) {
      throw new System.DivideByZeroException(message);
    }

    static void ThrowArgumentOutOfRangeException(string message) {
      throw new System.ArgumentOutOfRangeException(message);
    }

    static void ThrowNullReferenceException(string message) {
      throw new System.NullReferenceException(message);
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_lasso(systemDelegate, outOfMemoryDelegate, indexOutOfRangeDelegate, divideByZeroDelegate, argumentOutOfRangeDelegate, nullReferenceDelegate);
    }
  }

  static SWIGExceptionHelper exceptionHelper = new SWIGExceptionHelper();


  class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [DllImport("lasso", EntryPoint="SWIGRegisterStringCallback_lasso")]
    public static extern void SWIGRegisterStringCallback_lasso(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_lasso(stringDelegate);
    }
  }

  static SWIGStringHelper stringHelper = new SWIGStringHelper();


  [DllImport("lasso", EntryPoint="CSharp_init")]
  public static extern int init();

  [DllImport("lasso", EntryPoint="CSharp_shutdown")]
  public static extern int shutdown();

  [DllImport("lasso", EntryPoint="CSharp_get_httpMethodAny")]
  public static extern int get_httpMethodAny();

  [DllImport("lasso", EntryPoint="CSharp_get_httpMethodGet")]
  public static extern int get_httpMethodGet();

  [DllImport("lasso", EntryPoint="CSharp_get_httpMethodPost")]
  public static extern int get_httpMethodPost();

  [DllImport("lasso", EntryPoint="CSharp_get_httpMethodRedirect")]
  public static extern int get_httpMethodRedirect();

  [DllImport("lasso", EntryPoint="CSharp_get_httpMethodSoap")]
  public static extern int get_httpMethodSoap();

  [DllImport("lasso", EntryPoint="CSharp_get_libConsentObtained")]
  public static extern string get_libConsentObtained();

  [DllImport("lasso", EntryPoint="CSharp_get_libConsentUnavailable")]
  public static extern string get_libConsentUnavailable();

  [DllImport("lasso", EntryPoint="CSharp_get_libConsentInapplicable")]
  public static extern string get_libConsentInapplicable();

  [DllImport("lasso", EntryPoint="CSharp_get_libNameIdPolicyTypeNone")]
  public static extern string get_libNameIdPolicyTypeNone();

  [DllImport("lasso", EntryPoint="CSharp_get_libNameIdPolicyTypeOneTime")]
  public static extern string get_libNameIdPolicyTypeOneTime();

  [DllImport("lasso", EntryPoint="CSharp_get_libNameIdPolicyTypeFederated")]
  public static extern string get_libNameIdPolicyTypeFederated();

  [DllImport("lasso", EntryPoint="CSharp_get_libNameIdPolicyTypeAny")]
  public static extern string get_libNameIdPolicyTypeAny();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileBrwsArt")]
  public static extern string get_libProtocolProfileBrwsArt();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileBrwsPost")]
  public static extern string get_libProtocolProfileBrwsPost();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileFedTermIdpHttp")]
  public static extern string get_libProtocolProfileFedTermIdpHttp();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileFedTermIdpSoap")]
  public static extern string get_libProtocolProfileFedTermIdpSoap();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileFedTermSpHttp")]
  public static extern string get_libProtocolProfileFedTermSpHttp();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileFedTermSpSoap")]
  public static extern string get_libProtocolProfileFedTermSpSoap();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileRniIdpHttp")]
  public static extern string get_libProtocolProfileRniIdpHttp();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileRniIdpSoap")]
  public static extern string get_libProtocolProfileRniIdpSoap();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileRniSpHttp")]
  public static extern string get_libProtocolProfileRniSpHttp();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileRniSpSoap")]
  public static extern string get_libProtocolProfileRniSpSoap();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileSloIdpHttp")]
  public static extern string get_libProtocolProfileSloIdpHttp();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileSloIdpSoap")]
  public static extern string get_libProtocolProfileSloIdpSoap();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileSloSpHttp")]
  public static extern string get_libProtocolProfileSloSpHttp();

  [DllImport("lasso", EntryPoint="CSharp_get_libProtocolProfileSloSpSoap")]
  public static extern string get_libProtocolProfileSloSpSoap();

  [DllImport("lasso", EntryPoint="CSharp_get_loginProtocolProfileBrwsArt")]
  public static extern int get_loginProtocolProfileBrwsArt();

  [DllImport("lasso", EntryPoint="CSharp_get_loginProtocolProfileBrwsPost")]
  public static extern int get_loginProtocolProfileBrwsPost();

  [DllImport("lasso", EntryPoint="CSharp_get_messageTypeNone")]
  public static extern int get_messageTypeNone();

  [DllImport("lasso", EntryPoint="CSharp_get_messageTypeAuthnRequest")]
  public static extern int get_messageTypeAuthnRequest();

  [DllImport("lasso", EntryPoint="CSharp_get_messageTypeAuthnResponse")]
  public static extern int get_messageTypeAuthnResponse();

  [DllImport("lasso", EntryPoint="CSharp_get_messageTypeRequest")]
  public static extern int get_messageTypeRequest();

  [DllImport("lasso", EntryPoint="CSharp_get_messageTypeResponse")]
  public static extern int get_messageTypeResponse();

  [DllImport("lasso", EntryPoint="CSharp_get_messageTypeArtifact")]
  public static extern int get_messageTypeArtifact();

  [DllImport("lasso", EntryPoint="CSharp_get_providerTypeNone")]
  public static extern int get_providerTypeNone();

  [DllImport("lasso", EntryPoint="CSharp_get_providerTypeSp")]
  public static extern int get_providerTypeSp();

  [DllImport("lasso", EntryPoint="CSharp_get_providerTypeIdp")]
  public static extern int get_providerTypeIdp();

  [DllImport("lasso", EntryPoint="CSharp_get_requestTypeInvalid")]
  public static extern int get_requestTypeInvalid();

  [DllImport("lasso", EntryPoint="CSharp_get_requestTypeLogin")]
  public static extern int get_requestTypeLogin();

  [DllImport("lasso", EntryPoint="CSharp_get_requestTypeLogout")]
  public static extern int get_requestTypeLogout();

  [DllImport("lasso", EntryPoint="CSharp_get_requestTypeDefederation")]
  public static extern int get_requestTypeDefederation();

  [DllImport("lasso", EntryPoint="CSharp_get_requestTypeRegisterNameIdentifier")]
  public static extern int get_requestTypeRegisterNameIdentifier();

  [DllImport("lasso", EntryPoint="CSharp_get_requestTypeNameIdentifierMapping")]
  public static extern int get_requestTypeNameIdentifierMapping();

  [DllImport("lasso", EntryPoint="CSharp_get_requestTypeLecp")]
  public static extern int get_requestTypeLecp();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodPassword")]
  public static extern string get_samlAuthenticationMethodPassword();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodKerberos")]
  public static extern string get_samlAuthenticationMethodKerberos();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodSecureRemotePassword")]
  public static extern string get_samlAuthenticationMethodSecureRemotePassword();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodHardwareToken")]
  public static extern string get_samlAuthenticationMethodHardwareToken();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodSmartcardPki")]
  public static extern string get_samlAuthenticationMethodSmartcardPki();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodSoftwarePki")]
  public static extern string get_samlAuthenticationMethodSoftwarePki();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodPgp")]
  public static extern string get_samlAuthenticationMethodPgp();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodSpki")]
  public static extern string get_samlAuthenticationMethodSpki();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodXkms")]
  public static extern string get_samlAuthenticationMethodXkms();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodXmlDsig")]
  public static extern string get_samlAuthenticationMethodXmlDsig();

  [DllImport("lasso", EntryPoint="CSharp_get_samlAuthenticationMethodUnspecified")]
  public static extern string get_samlAuthenticationMethodUnspecified();

  [DllImport("lasso", EntryPoint="CSharp_get_signatureMethodRsaSha1")]
  public static extern int get_signatureMethodRsaSha1();

  [DllImport("lasso", EntryPoint="CSharp_get_signatureMethodDsaSha1")]
  public static extern int get_signatureMethodDsaSha1();

  [DllImport("lasso", EntryPoint="CSharp_get_XML_ERROR_NODE_NOT_FOUND")]
  public static extern int get_XML_ERROR_NODE_NOT_FOUND();

  [DllImport("lasso", EntryPoint="CSharp_get_XML_ERROR_NODE_CONTENT_NOT_FOUND")]
  public static extern int get_XML_ERROR_NODE_CONTENT_NOT_FOUND();

  [DllImport("lasso", EntryPoint="CSharp_get_XML_ERROR_ATTR_NOT_FOUND")]
  public static extern int get_XML_ERROR_ATTR_NOT_FOUND();

  [DllImport("lasso", EntryPoint="CSharp_get_XML_ERROR_ATTR_VALUE_NOT_FOUND")]
  public static extern int get_XML_ERROR_ATTR_VALUE_NOT_FOUND();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_SIGNATURE_TMPL_CREATION_FAILED")]
  public static extern int get_DS_ERROR_SIGNATURE_TMPL_CREATION_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_CONTEXT_CREATION_FAILED")]
  public static extern int get_DS_ERROR_CONTEXT_CREATION_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_PUBLIC_KEY_LOAD_FAILED")]
  public static extern int get_DS_ERROR_PUBLIC_KEY_LOAD_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_PRIVATE_KEY_LOAD_FAILED")]
  public static extern int get_DS_ERROR_PRIVATE_KEY_LOAD_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_CERTIFICATE_LOAD_FAILED")]
  public static extern int get_DS_ERROR_CERTIFICATE_LOAD_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_SIGNATURE_FAILED")]
  public static extern int get_DS_ERROR_SIGNATURE_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_SIGNATURE_NOT_FOUND")]
  public static extern int get_DS_ERROR_SIGNATURE_NOT_FOUND();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_KEYS_MNGR_CREATION_FAILED")]
  public static extern int get_DS_ERROR_KEYS_MNGR_CREATION_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_KEYS_MNGR_INIT_FAILED")]
  public static extern int get_DS_ERROR_KEYS_MNGR_INIT_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_SIGNATURE_VERIFICATION_FAILED")]
  public static extern int get_DS_ERROR_SIGNATURE_VERIFICATION_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_DS_ERROR_INVALID_SIGNATURE")]
  public static extern int get_DS_ERROR_INVALID_SIGNATURE();

  [DllImport("lasso", EntryPoint="CSharp_get_SERVER_ERROR_PROVIDER_NOT_FOUND")]
  public static extern int get_SERVER_ERROR_PROVIDER_NOT_FOUND();

  [DllImport("lasso", EntryPoint="CSharp_get_SERVER_ERROR_ADD_PROVIDER_FAILED")]
  public static extern int get_SERVER_ERROR_ADD_PROVIDER_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_LOGOUT_ERROR_UNSUPPORTED_PROFILE")]
  public static extern int get_LOGOUT_ERROR_UNSUPPORTED_PROFILE();

  [DllImport("lasso", EntryPoint="CSharp_get_PROFILE_ERROR_INVALID_QUERY")]
  public static extern int get_PROFILE_ERROR_INVALID_QUERY();

  [DllImport("lasso", EntryPoint="CSharp_get_PROFILE_ERROR_MISSING_REQUEST")]
  public static extern int get_PROFILE_ERROR_MISSING_REQUEST();

  [DllImport("lasso", EntryPoint="CSharp_get_PARAM_ERROR_BADTYPE_OR_NULL_OBJ")]
  public static extern int get_PARAM_ERROR_BADTYPE_OR_NULL_OBJ();

  [DllImport("lasso", EntryPoint="CSharp_get_PARAM_ERROR_INVALID_VALUE")]
  public static extern int get_PARAM_ERROR_INVALID_VALUE();

  [DllImport("lasso", EntryPoint="CSharp_get_PARAM_ERROR_ERR_CHECK_FAILED")]
  public static extern int get_PARAM_ERROR_ERR_CHECK_FAILED();

  [DllImport("lasso", EntryPoint="CSharp_get_ERROR_UNDEFINED")]
  public static extern int get_ERROR_UNDEFINED();

  [DllImport("lasso", EntryPoint="CSharp_new_Assertion")]
  public static extern IntPtr new_Assertion(string jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_delete_Assertion")]
  public static extern void delete_Assertion(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Assertion_dump")]
  public static extern string Assertion_dump(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_AuthnRequest_affiliationId")]
  public static extern void set_AuthnRequest_affiliationId(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_AuthnRequest_affiliationId")]
  public static extern string get_AuthnRequest_affiliationId(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_AuthnRequest_assertionConsumerServiceId")]
  public static extern void set_AuthnRequest_assertionConsumerServiceId(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_AuthnRequest_assertionConsumerServiceId")]
  public static extern string get_AuthnRequest_assertionConsumerServiceId(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_AuthnRequest_consent")]
  public static extern void set_AuthnRequest_consent(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_AuthnRequest_consent")]
  public static extern string get_AuthnRequest_consent(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_AuthnRequest_forceAuthn")]
  public static extern void set_AuthnRequest_forceAuthn(IntPtr jarg1, bool jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_AuthnRequest_forceAuthn")]
  public static extern bool get_AuthnRequest_forceAuthn(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_AuthnRequest_isPassive")]
  public static extern void set_AuthnRequest_isPassive(IntPtr jarg1, bool jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_AuthnRequest_isPassive")]
  public static extern bool get_AuthnRequest_isPassive(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_AuthnRequest_nameIdPolicy")]
  public static extern void set_AuthnRequest_nameIdPolicy(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_AuthnRequest_nameIdPolicy")]
  public static extern string get_AuthnRequest_nameIdPolicy(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_AuthnRequest_protocolProfile")]
  public static extern void set_AuthnRequest_protocolProfile(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_AuthnRequest_protocolProfile")]
  public static extern string get_AuthnRequest_protocolProfile(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_AuthnRequest_providerId")]
  public static extern void set_AuthnRequest_providerId(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_AuthnRequest_providerId")]
  public static extern string get_AuthnRequest_providerId(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_AuthnRequest_relayState")]
  public static extern void set_AuthnRequest_relayState(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_AuthnRequest_relayState")]
  public static extern string get_AuthnRequest_relayState(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_LogoutRequest_relayState")]
  public static extern void set_LogoutRequest_relayState(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_LogoutRequest_relayState")]
  public static extern string get_LogoutRequest_relayState(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Server_providerId")]
  public static extern string get_Server_providerId(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_new_Server")]
  public static extern IntPtr new_Server(string jarg1, string jarg2, string jarg3, string jarg4, int jarg5);

  [DllImport("lasso", EntryPoint="CSharp_delete_Server")]
  public static extern void delete_Server(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Server_newFromDump")]
  public static extern IntPtr Server_newFromDump(string jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Server_addProvider")]
  public static extern void Server_addProvider(IntPtr jarg1, string jarg2, string jarg3, string jarg4);

  [DllImport("lasso", EntryPoint="CSharp_Server_dump")]
  public static extern string Server_dump(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Identity_isDirty")]
  public static extern bool get_Identity_isDirty(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_new_Identity")]
  public static extern IntPtr new_Identity();

  [DllImport("lasso", EntryPoint="CSharp_delete_Identity")]
  public static extern void delete_Identity(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Identity_newFromDump")]
  public static extern IntPtr Identity_newFromDump(string jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Identity_dump")]
  public static extern string Identity_dump(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Session_isDirty")]
  public static extern bool get_Session_isDirty(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_new_Session")]
  public static extern IntPtr new_Session();

  [DllImport("lasso", EntryPoint="CSharp_delete_Session")]
  public static extern void delete_Session(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Session_newFromDump")]
  public static extern IntPtr Session_newFromDump(string jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Session_dump")]
  public static extern string Session_dump(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Session_getAuthenticationMethod")]
  public static extern string Session_getAuthenticationMethod(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_getRequestTypeFromSoapMsg")]
  public static extern int getRequestTypeFromSoapMsg(string jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Defederation_identity")]
  public static extern void set_Defederation_identity(IntPtr jarg1, IntPtr jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Defederation_identity")]
  public static extern IntPtr get_Defederation_identity(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Defederation_isIdentityDirty")]
  public static extern bool get_Defederation_isIdentityDirty(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Defederation_isSessionDirty")]
  public static extern bool get_Defederation_isSessionDirty(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Defederation_msgBody")]
  public static extern string get_Defederation_msgBody(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Defederation_msgRelayState")]
  public static extern string get_Defederation_msgRelayState(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Defederation_msgUrl")]
  public static extern string get_Defederation_msgUrl(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Defederation_nameIdentifier")]
  public static extern string get_Defederation_nameIdentifier(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Defederation_remoteProviderId")]
  public static extern void set_Defederation_remoteProviderId(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Defederation_remoteProviderId")]
  public static extern string get_Defederation_remoteProviderId(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Defederation_request")]
  public static extern IntPtr get_Defederation_request(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Defederation_session")]
  public static extern void set_Defederation_session(IntPtr jarg1, IntPtr jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Defederation_session")]
  public static extern IntPtr get_Defederation_session(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_new_Defederation")]
  public static extern IntPtr new_Defederation(IntPtr jarg1, int jarg2);

  [DllImport("lasso", EntryPoint="CSharp_delete_Defederation")]
  public static extern void delete_Defederation(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Defederation_setIdentityFromDump")]
  public static extern void Defederation_setIdentityFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Defederation_setSessionFromDump")]
  public static extern void Defederation_setSessionFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Defederation_buildNotificationMsg")]
  public static extern void Defederation_buildNotificationMsg(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Defederation_initNotification")]
  public static extern void Defederation_initNotification(IntPtr jarg1, string jarg2, int jarg3);

  [DllImport("lasso", EntryPoint="CSharp_Defederation_processNotificationMsg")]
  public static extern void Defederation_processNotificationMsg(IntPtr jarg1, string jarg2, int jarg3);

  [DllImport("lasso", EntryPoint="CSharp_Defederation_validateNotification")]
  public static extern void Defederation_validateNotification(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_assertionArtifact")]
  public static extern string get_Login_assertionArtifact(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_protocolProfile")]
  public static extern int get_Login_protocolProfile(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_authnRequest")]
  public static extern IntPtr get_Login_authnRequest(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_authnResponse")]
  public static extern IntPtr get_Login_authnResponse(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Login_identity")]
  public static extern void set_Login_identity(IntPtr jarg1, IntPtr jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_identity")]
  public static extern IntPtr get_Login_identity(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_isIdentityDirty")]
  public static extern bool get_Login_isIdentityDirty(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_isSessionDirty")]
  public static extern bool get_Login_isSessionDirty(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_msgBody")]
  public static extern string get_Login_msgBody(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_msgRelayState")]
  public static extern string get_Login_msgRelayState(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_msgUrl")]
  public static extern string get_Login_msgUrl(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_nameIdentifier")]
  public static extern string get_Login_nameIdentifier(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Login_remoteProviderId")]
  public static extern void set_Login_remoteProviderId(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_remoteProviderId")]
  public static extern string get_Login_remoteProviderId(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_request")]
  public static extern IntPtr get_Login_request(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_response")]
  public static extern IntPtr get_Login_response(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Login_responseStatus")]
  public static extern void set_Login_responseStatus(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_responseStatus")]
  public static extern string get_Login_responseStatus(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Login_session")]
  public static extern void set_Login_session(IntPtr jarg1, IntPtr jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_session")]
  public static extern IntPtr get_Login_session(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Login_assertion")]
  public static extern void set_Login_assertion(IntPtr jarg1, IntPtr jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Login_assertion")]
  public static extern IntPtr get_Login_assertion(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_new_Login")]
  public static extern IntPtr new_Login(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_delete_Login")]
  public static extern void delete_Login(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Login_newFromDump")]
  public static extern IntPtr Login_newFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Login_setAssertionFromDump")]
  public static extern void Login_setAssertionFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Login_setIdentityFromDump")]
  public static extern void Login_setIdentityFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Login_setSessionFromDump")]
  public static extern void Login_setSessionFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Login_acceptSso")]
  public static extern void Login_acceptSso(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Login_buildArtifactMsg")]
  public static extern void Login_buildArtifactMsg(IntPtr jarg1, int jarg2, string jarg3, string jarg4, int jarg5);

  [DllImport("lasso", EntryPoint="CSharp_Login_buildAuthnRequestMsg")]
  public static extern void Login_buildAuthnRequestMsg(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Login_buildAuthnResponseMsg")]
  public static extern void Login_buildAuthnResponseMsg(IntPtr jarg1, int jarg2, string jarg3, string jarg4);

  [DllImport("lasso", EntryPoint="CSharp_Login_buildRequestMsg")]
  public static extern void Login_buildRequestMsg(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Login_buildResponseMsg")]
  public static extern void Login_buildResponseMsg(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Login_dump")]
  public static extern string Login_dump(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Login_initAuthnRequest")]
  public static extern void Login_initAuthnRequest(IntPtr jarg1, int jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Login_initFromAuthnRequestMsg")]
  public static extern void Login_initFromAuthnRequestMsg(IntPtr jarg1, string jarg2, int jarg3);

  [DllImport("lasso", EntryPoint="CSharp_Login_initRequest")]
  public static extern void Login_initRequest(IntPtr jarg1, string jarg2, int jarg3);

  [DllImport("lasso", EntryPoint="CSharp_Login_mustAuthenticate")]
  public static extern bool Login_mustAuthenticate(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Login_processAuthnResponseMsg")]
  public static extern void Login_processAuthnResponseMsg(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Login_processRequestMsg")]
  public static extern void Login_processRequestMsg(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Login_processResponseMsg")]
  public static extern void Login_processResponseMsg(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_set_Logout_identity")]
  public static extern void set_Logout_identity(IntPtr jarg1, IntPtr jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_identity")]
  public static extern IntPtr get_Logout_identity(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_isIdentityDirty")]
  public static extern bool get_Logout_isIdentityDirty(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_isSessionDirty")]
  public static extern bool get_Logout_isSessionDirty(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_msgBody")]
  public static extern string get_Logout_msgBody(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_msgRelayState")]
  public static extern string get_Logout_msgRelayState(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_msgUrl")]
  public static extern string get_Logout_msgUrl(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_nameIdentifier")]
  public static extern string get_Logout_nameIdentifier(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Logout_remoteProviderId")]
  public static extern void set_Logout_remoteProviderId(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_remoteProviderId")]
  public static extern string get_Logout_remoteProviderId(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_request")]
  public static extern IntPtr get_Logout_request(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_response")]
  public static extern IntPtr get_Logout_response(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Logout_responseStatus")]
  public static extern void set_Logout_responseStatus(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_responseStatus")]
  public static extern string get_Logout_responseStatus(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Logout_session")]
  public static extern void set_Logout_session(IntPtr jarg1, IntPtr jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Logout_session")]
  public static extern IntPtr get_Logout_session(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_new_Logout")]
  public static extern IntPtr new_Logout(IntPtr jarg1, int jarg2);

  [DllImport("lasso", EntryPoint="CSharp_delete_Logout")]
  public static extern void delete_Logout(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Logout_newFromDump")]
  public static extern IntPtr Logout_newFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Logout_setIdentityFromDump")]
  public static extern void Logout_setIdentityFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Logout_setSessionFromDump")]
  public static extern void Logout_setSessionFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Logout_buildRequestMsg")]
  public static extern void Logout_buildRequestMsg(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Logout_buildResponseMsg")]
  public static extern void Logout_buildResponseMsg(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Logout_dump")]
  public static extern string Logout_dump(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Logout_getNextProviderId")]
  public static extern string Logout_getNextProviderId(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Logout_initRequest")]
  public static extern void Logout_initRequest(IntPtr jarg1, string jarg2, int jarg3);

  [DllImport("lasso", EntryPoint="CSharp_Logout_processRequestMsg")]
  public static extern void Logout_processRequestMsg(IntPtr jarg1, string jarg2, int jarg3);

  [DllImport("lasso", EntryPoint="CSharp_Logout_processResponseMsg")]
  public static extern void Logout_processResponseMsg(IntPtr jarg1, string jarg2, int jarg3);

  [DllImport("lasso", EntryPoint="CSharp_Logout_resetProviderIdIndex")]
  public static extern void Logout_resetProviderIdIndex(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Logout_validateRequest")]
  public static extern void Logout_validateRequest(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_authnRequest")]
  public static extern IntPtr get_Lecp_authnRequest(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_authnResponse")]
  public static extern IntPtr get_Lecp_authnResponse(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Lecp_identity")]
  public static extern void set_Lecp_identity(IntPtr jarg1, IntPtr jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_identity")]
  public static extern IntPtr get_Lecp_identity(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_isIdentityDirty")]
  public static extern bool get_Lecp_isIdentityDirty(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_isSessionDirty")]
  public static extern bool get_Lecp_isSessionDirty(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_msgBody")]
  public static extern string get_Lecp_msgBody(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_msgRelayState")]
  public static extern string get_Lecp_msgRelayState(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_msgUrl")]
  public static extern string get_Lecp_msgUrl(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_nameIdentifier")]
  public static extern string get_Lecp_nameIdentifier(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Lecp_remoteProviderId")]
  public static extern void set_Lecp_remoteProviderId(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_remoteProviderId")]
  public static extern string get_Lecp_remoteProviderId(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_request")]
  public static extern IntPtr get_Lecp_request(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_response")]
  public static extern IntPtr get_Lecp_response(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Lecp_responseStatus")]
  public static extern void set_Lecp_responseStatus(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_responseStatus")]
  public static extern string get_Lecp_responseStatus(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_set_Lecp_session")]
  public static extern void set_Lecp_session(IntPtr jarg1, IntPtr jarg2);

  [DllImport("lasso", EntryPoint="CSharp_get_Lecp_session")]
  public static extern IntPtr get_Lecp_session(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_new_Lecp")]
  public static extern IntPtr new_Lecp(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_delete_Lecp")]
  public static extern void delete_Lecp(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Lecp_setIdentityFromDump")]
  public static extern void Lecp_setIdentityFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Lecp_setSessionFromDump")]
  public static extern void Lecp_setSessionFromDump(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Lecp_buildAuthnRequestEnvelopeMsg")]
  public static extern void Lecp_buildAuthnRequestEnvelopeMsg(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Lecp_buildAuthnRequestMsg")]
  public static extern void Lecp_buildAuthnRequestMsg(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Lecp_buildAuthnResponseEnvelopeMsg")]
  public static extern void Lecp_buildAuthnResponseEnvelopeMsg(IntPtr jarg1, int jarg2, string jarg3, string jarg4);

  [DllImport("lasso", EntryPoint="CSharp_Lecp_buildAuthnResponseMsg")]
  public static extern void Lecp_buildAuthnResponseMsg(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Lecp_initAuthnRequest")]
  public static extern void Lecp_initAuthnRequest(IntPtr jarg1);

  [DllImport("lasso", EntryPoint="CSharp_Lecp_initFromAuthnRequestMsg")]
  public static extern void Lecp_initFromAuthnRequestMsg(IntPtr jarg1, string jarg2, int jarg3);

  [DllImport("lasso", EntryPoint="CSharp_Lecp_processAuthnRequestEnvelopeMsg")]
  public static extern void Lecp_processAuthnRequestEnvelopeMsg(IntPtr jarg1, string jarg2);

  [DllImport("lasso", EntryPoint="CSharp_Lecp_processAuthnResponseEnvelopeMsg")]
  public static extern void Lecp_processAuthnResponseEnvelopeMsg(IntPtr jarg1, string jarg2);
}
