/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class LibLogoutResponse : LibStatusResponse, IDisposable {
  internal LibLogoutResponse(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static IntPtr getCPtr(LibLogoutResponse obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~LibLogoutResponse() {
    Dispose();
  }

  public virtual void Dispose() {
  base.Dispose();
}

  public StringList extension {
    set {
      lassoPINVOKE.set_LibLogoutResponse_extension(swigCPtr, StringList.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_LibLogoutResponse_extension(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new StringList(cPtr, false);
    } 
  }

  public string providerId {
    set {
      lassoPINVOKE.set_LibLogoutResponse_providerId(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_LibLogoutResponse_providerId(swigCPtr);
    } 
  }

  public string relayState {
    set {
      lassoPINVOKE.set_LibLogoutResponse_relayState(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_LibLogoutResponse_relayState(swigCPtr);
    } 
  }

  public SamlpStatus status {
    set {
      lassoPINVOKE.set_LibLogoutResponse_status(swigCPtr, SamlpStatus.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_LibLogoutResponse_status(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlpStatus(cPtr, false);
    } 
  }

  public LibLogoutResponse() : this(lassoPINVOKE.new_LibLogoutResponse(), true) {
  }

  public static LibLogoutResponse newFull(string providerID, string statusCodeValue, LibLogoutRequest request, SWIGTYPE_p_LassoSignatureType sign_type, SignatureMethod sign_method) {
    IntPtr cPtr = lassoPINVOKE.LibLogoutResponse_newFull(providerID, statusCodeValue, LibLogoutRequest.getCPtr(request), SWIGTYPE_p_LassoSignatureType.getCPtr(sign_type), (int)sign_method);
    return (cPtr == IntPtr.Zero) ? null : new LibLogoutResponse(cPtr, true);
  }

  public string dump() {
    return lassoPINVOKE.LibLogoutResponse_dump(swigCPtr);
  }

}

}
