/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class Logout : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal Logout(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(Logout obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected Logout() : this(IntPtr.Zero, false) {
  }

  ~Logout() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      lassoPINVOKE.delete_Logout(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public Identity identity {
    set {
      lassoPINVOKE.set_Logout_identity(swigCPtr, Identity.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_Logout_identity(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new Identity(cPtr, false);
    } 
  }

  public bool isIdentityDirty {
    get {
      return lassoPINVOKE.get_Logout_isIdentityDirty(swigCPtr);
    } 
  }

  public bool isSessionDirty {
    get {
      return lassoPINVOKE.get_Logout_isSessionDirty(swigCPtr);
    } 
  }

  public string msgBody {
    get {
      return lassoPINVOKE.get_Logout_msgBody(swigCPtr);
    } 
  }

  public string msgRelayState {
    get {
      return lassoPINVOKE.get_Logout_msgRelayState(swigCPtr);
    } 
  }

  public string msgUrl {
    get {
      return lassoPINVOKE.get_Logout_msgUrl(swigCPtr);
    } 
  }

  public SamlNameIdentifier nameIdentifier {
    set {
      lassoPINVOKE.set_Logout_nameIdentifier(swigCPtr, SamlNameIdentifier.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_Logout_nameIdentifier(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlNameIdentifier(cPtr, false);
    } 
  }

  public string remoteProviderId {
    set {
      lassoPINVOKE.set_Logout_remoteProviderId(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_Logout_remoteProviderId(swigCPtr);
    } 
  }

  public SamlpRequestAbstract request {
    set {
      lassoPINVOKE.set_Logout_request(swigCPtr, SamlpRequestAbstract.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_Logout_request(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlpRequestAbstract(cPtr, false);
    } 
  }

  public SamlpResponseAbstract response {
    set {
      lassoPINVOKE.set_Logout_response(swigCPtr, SamlpResponseAbstract.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_Logout_response(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlpResponseAbstract(cPtr, false);
    } 
  }

  public Server server {
    set {
      lassoPINVOKE.set_Logout_server(swigCPtr, Server.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_Logout_server(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new Server(cPtr, false);
    } 
  }

  public Session session {
    set {
      lassoPINVOKE.set_Logout_session(swigCPtr, Session.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_Logout_session(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new Session(cPtr, false);
    } 
  }

  public Logout(Server server) : this(lassoPINVOKE.new_Logout(Server.getCPtr(server)), true) {
  }

  public static Logout newFromDump(Server server, string dump) {
    IntPtr cPtr = lassoPINVOKE.Logout_newFromDump(Server.getCPtr(server), dump);
    return (cPtr == IntPtr.Zero) ? null : new Logout(cPtr, true);
  }

  public int setIdentityFromDump(string dump) {
    return lassoPINVOKE.Logout_setIdentityFromDump(swigCPtr, dump);
  }

  public int setSessionFromDump(string dump) {
    return lassoPINVOKE.Logout_setSessionFromDump(swigCPtr, dump);
  }

  public int buildRequestMsg() {
    return lassoPINVOKE.Logout_buildRequestMsg(swigCPtr);
  }

  public int buildResponseMsg() {
    return lassoPINVOKE.Logout_buildResponseMsg(swigCPtr);
  }

  public string dump() {
    return lassoPINVOKE.Logout_dump(swigCPtr);
  }

  public string getNextProviderId() {
    return lassoPINVOKE.Logout_getNextProviderId(swigCPtr);
  }

  public int initRequest(string remoteProviderId, HttpMethod httpMethod) {
    return lassoPINVOKE.Logout_initRequest(swigCPtr, remoteProviderId, (int)httpMethod);
  }

  public int processRequestMsg(string requestMsg) {
    return lassoPINVOKE.Logout_processRequestMsg(swigCPtr, requestMsg);
  }

  public int processResponseMsg(string responseMsg) {
    return lassoPINVOKE.Logout_processResponseMsg(swigCPtr, responseMsg);
  }

  public int resetProviderIdIndex() {
    return lassoPINVOKE.Logout_resetProviderIdIndex(swigCPtr);
  }

  public int validateRequest() {
    return lassoPINVOKE.Logout_validateRequest(swigCPtr);
  }

}

}
