/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class NameRegistration : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal NameRegistration(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(NameRegistration obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected NameRegistration() : this(IntPtr.Zero, false) {
  }

  ~NameRegistration() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      lassoPINVOKE.delete_NameRegistration(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public Identity identity {
    set {
      lassoPINVOKE.set_NameRegistration_identity(swigCPtr, Identity.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_NameRegistration_identity(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new Identity(cPtr, false);
    } 
  }

  public bool isIdentityDirty {
    get {
      return lassoPINVOKE.get_NameRegistration_isIdentityDirty(swigCPtr);
    } 
  }

  public bool isSessionDirty {
    get {
      return lassoPINVOKE.get_NameRegistration_isSessionDirty(swigCPtr);
    } 
  }

  public string msgBody {
    get {
      return lassoPINVOKE.get_NameRegistration_msgBody(swigCPtr);
    } 
  }

  public string msgRelayState {
    get {
      return lassoPINVOKE.get_NameRegistration_msgRelayState(swigCPtr);
    } 
  }

  public string msgUrl {
    get {
      return lassoPINVOKE.get_NameRegistration_msgUrl(swigCPtr);
    } 
  }

  public SamlNameIdentifier nameIdentifier {
    set {
      lassoPINVOKE.set_NameRegistration_nameIdentifier(swigCPtr, SamlNameIdentifier.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_NameRegistration_nameIdentifier(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlNameIdentifier(cPtr, false);
    } 
  }

  public string remoteProviderId {
    set {
      lassoPINVOKE.set_NameRegistration_remoteProviderId(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_NameRegistration_remoteProviderId(swigCPtr);
    } 
  }

  public SamlpRequestAbstract request {
    set {
      lassoPINVOKE.set_NameRegistration_request(swigCPtr, SamlpRequestAbstract.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_NameRegistration_request(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlpRequestAbstract(cPtr, false);
    } 
  }

  public SamlpResponseAbstract response {
    set {
      lassoPINVOKE.set_NameRegistration_response(swigCPtr, SamlpResponseAbstract.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_NameRegistration_response(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlpResponseAbstract(cPtr, false);
    } 
  }

  public Server server {
    set {
      lassoPINVOKE.set_NameRegistration_server(swigCPtr, Server.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_NameRegistration_server(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new Server(cPtr, false);
    } 
  }

  public Session session {
    set {
      lassoPINVOKE.set_NameRegistration_session(swigCPtr, Session.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_NameRegistration_session(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new Session(cPtr, false);
    } 
  }

  public SamlNameIdentifier oldNameIdentifier {
    set {
      lassoPINVOKE.set_NameRegistration_oldNameIdentifier(swigCPtr, SamlNameIdentifier.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_NameRegistration_oldNameIdentifier(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlNameIdentifier(cPtr, false);
    } 
  }

  public NameRegistration(Server server) : this(lassoPINVOKE.new_NameRegistration(Server.getCPtr(server)), true) {
  }

  public static NameRegistration newFromDump(Server server, string dump) {
    IntPtr cPtr = lassoPINVOKE.NameRegistration_newFromDump(Server.getCPtr(server), dump);
    return (cPtr == IntPtr.Zero) ? null : new NameRegistration(cPtr, true);
  }

  public int setIdentityFromDump(string dump) {
    return lassoPINVOKE.NameRegistration_setIdentityFromDump(swigCPtr, dump);
  }

  public int setSessionFromDump(string dump) {
    return lassoPINVOKE.NameRegistration_setSessionFromDump(swigCPtr, dump);
  }

  public int buildRequestMsg() {
    return lassoPINVOKE.NameRegistration_buildRequestMsg(swigCPtr);
  }

  public int buildResponseMsg() {
    return lassoPINVOKE.NameRegistration_buildResponseMsg(swigCPtr);
  }

  public string dump() {
    return lassoPINVOKE.NameRegistration_dump(swigCPtr);
  }

  public int initRequest(string remoteProviderId, HttpMethod httpMethod) {
    return lassoPINVOKE.NameRegistration_initRequest(swigCPtr, remoteProviderId, (int)httpMethod);
  }

  public int processRequestMsg(string requestMsg) {
    return lassoPINVOKE.NameRegistration_processRequestMsg(swigCPtr, requestMsg);
  }

  public int processResponseMsg(string responseMsg) {
    return lassoPINVOKE.NameRegistration_processResponseMsg(swigCPtr, responseMsg);
  }

  public int validateRequest() {
    return lassoPINVOKE.NameRegistration_validateRequest(swigCPtr);
  }

}

}
