/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

public enum ProviderRole {
  PROVIDER_ROLE_NONE = 0,
  PROVIDER_ROLE_SP,
  PROVIDER_ROLE_IDP
}


}
