/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

public enum RequestType {
  REQUEST_TYPE_INVALID = 0,
  REQUEST_TYPE_LOGIN = 1,
  REQUEST_TYPE_LOGOUT = 2,
  REQUEST_TYPE_DEFEDERATION = 3,
  REQUEST_TYPE_NAME_REGISTRATION = 4,
  REQUEST_TYPE_NAME_IDENTIFIER_MAPPING = 5,
  REQUEST_TYPE_LECP = 6,
  REQUEST_TYPE_DISCO_QUERY = 7,
  REQUEST_TYPE_DISCO_MODIFY = 8,
  REQUEST_TYPE_DST_QUERY = 9,
  REQUEST_TYPE_DST_MODIFY = 10,
  REQUEST_TYPE_SASL_REQUEST = 11
}


}
