/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class SamlConditions : Node, IDisposable {
  internal SamlConditions(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static IntPtr getCPtr(SamlConditions obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~SamlConditions() {
    Dispose();
  }

  public virtual void Dispose() {
  base.Dispose();
}

  public string notBefore {
    set {
      lassoPINVOKE.set_SamlConditions_notBefore(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlConditions_notBefore(swigCPtr);
    } 
  }

  public string notOnOrAfter {
    set {
      lassoPINVOKE.set_SamlConditions_notOnOrAfter(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlConditions_notOnOrAfter(swigCPtr);
    } 
  }

  public NodeList audienceRestrictionCondition {
    set {
      lassoPINVOKE.set_SamlConditions_audienceRestrictionCondition(swigCPtr, NodeList.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlConditions_audienceRestrictionCondition(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new NodeList(cPtr, false);
    } 
  }

  public NodeList condition {
    set {
      lassoPINVOKE.set_SamlConditions_condition(swigCPtr, NodeList.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlConditions_condition(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new NodeList(cPtr, false);
    } 
  }

  public SamlConditions() : this(lassoPINVOKE.new_SamlConditions(), true) {
  }

  public string dump() {
    return lassoPINVOKE.SamlConditions_dump(swigCPtr);
  }

}

}
