/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class SamlSubjectStatementAbstract : SamlStatementAbstract, IDisposable {
  internal SamlSubjectStatementAbstract(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static IntPtr getCPtr(SamlSubjectStatementAbstract obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected SamlSubjectStatementAbstract() : this(IntPtr.Zero, false) {
  }

  public virtual void Dispose() {
  base.Dispose();
}

  public SamlSubject subject {
    set {
      lassoPINVOKE.set_SamlSubjectStatementAbstract_subject(swigCPtr, SamlSubject.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlSubjectStatementAbstract_subject(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlSubject(cPtr, false);
    } 
  }

  public string dump() {
    return lassoPINVOKE.SamlSubjectStatementAbstract_dump(swigCPtr);
  }

}

}
