/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class SamlAudienceRestrictionCondition : SamlConditionAbstract, IDisposable {
  internal SamlAudienceRestrictionCondition(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static IntPtr getCPtr(SamlAudienceRestrictionCondition obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~SamlAudienceRestrictionCondition() {
    Dispose();
  }

  public virtual void Dispose() {
  base.Dispose();
}

  public StringList audience {
    set {
      lassoPINVOKE.set_SamlAudienceRestrictionCondition_audience(swigCPtr, StringList.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlAudienceRestrictionCondition_audience(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new StringList(cPtr, false);
    } 
  }

  public SamlAudienceRestrictionCondition() : this(lassoPINVOKE.new_SamlAudienceRestrictionCondition(), true) {
  }

  public string dump() {
    return lassoPINVOKE.SamlAudienceRestrictionCondition_dump(swigCPtr);
  }

}

}
