/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class SamlSubjectLocality : Node, IDisposable {
  internal SamlSubjectLocality(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static IntPtr getCPtr(SamlSubjectLocality obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~SamlSubjectLocality() {
    Dispose();
  }

  public virtual void Dispose() {
  base.Dispose();
}

  public string dnsAddress {
    set {
      lassoPINVOKE.set_SamlSubjectLocality_dnsAddress(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlSubjectLocality_dnsAddress(swigCPtr);
    } 
  }

  public string ipAddress {
    set {
      lassoPINVOKE.set_SamlSubjectLocality_ipAddress(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlSubjectLocality_ipAddress(swigCPtr);
    } 
  }

  public SamlSubjectLocality() : this(lassoPINVOKE.new_SamlSubjectLocality(), true) {
  }

  public string dump() {
    return lassoPINVOKE.SamlSubjectLocality_dump(swigCPtr);
  }

}

}
