/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class SamlAuthenticationStatement : SamlSubjectStatementAbstract, IDisposable {
  internal SamlAuthenticationStatement(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static IntPtr getCPtr(SamlAuthenticationStatement obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~SamlAuthenticationStatement() {
    Dispose();
  }

  public virtual void Dispose() {
  base.Dispose();
}

  public string authenticationInstant {
    set {
      lassoPINVOKE.set_SamlAuthenticationStatement_authenticationInstant(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlAuthenticationStatement_authenticationInstant(swigCPtr);
    } 
  }

  public string authenticationMethod {
    set {
      lassoPINVOKE.set_SamlAuthenticationStatement_authenticationMethod(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlAuthenticationStatement_authenticationMethod(swigCPtr);
    } 
  }

  public NodeList authorityBinding {
    set {
      lassoPINVOKE.set_SamlAuthenticationStatement_authorityBinding(swigCPtr, NodeList.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlAuthenticationStatement_authorityBinding(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new NodeList(cPtr, false);
    } 
  }

  public SamlSubjectLocality subjectLocality {
    set {
      lassoPINVOKE.set_SamlAuthenticationStatement_subjectLocality(swigCPtr, SamlSubjectLocality.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlAuthenticationStatement_subjectLocality(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlSubjectLocality(cPtr, false);
    } 
  }

  public SamlAuthenticationStatement() : this(lassoPINVOKE.new_SamlAuthenticationStatement(), true) {
  }

  public string dump() {
    return lassoPINVOKE.SamlAuthenticationStatement_dump(swigCPtr);
  }

}

}
