/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class SamlSubjectStatement : SamlSubjectStatementAbstract, IDisposable {
  internal SamlSubjectStatement(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static IntPtr getCPtr(SamlSubjectStatement obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~SamlSubjectStatement() {
    Dispose();
  }

  public virtual void Dispose() {
  base.Dispose();
}

  public SamlSubject subject {
    set {
      lassoPINVOKE.set_SamlSubjectStatement_subject(swigCPtr, SamlSubject.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlSubjectStatement_subject(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlSubject(cPtr, false);
    } 
  }

  public SamlSubjectStatement() : this(lassoPINVOKE.new_SamlSubjectStatement(), true) {
  }

  public string dump() {
    return lassoPINVOKE.SamlSubjectStatement_dump(swigCPtr);
  }

}

}
