/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class SamlSubject : Node, IDisposable {
  internal SamlSubject(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static IntPtr getCPtr(SamlSubject obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~SamlSubject() {
    Dispose();
  }

  public virtual void Dispose() {
  base.Dispose();
}

  public SamlNameIdentifier nameIdentifier {
    set {
      lassoPINVOKE.set_SamlSubject_nameIdentifier(swigCPtr, SamlNameIdentifier.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlSubject_nameIdentifier(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlNameIdentifier(cPtr, false);
    } 
  }

  public SamlSubjectConfirmation subjectConfirmation {
    set {
      lassoPINVOKE.set_SamlSubject_subjectConfirmation(swigCPtr, SamlSubjectConfirmation.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlSubject_subjectConfirmation(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new SamlSubjectConfirmation(cPtr, false);
    } 
  }

  public SamlSubject() : this(lassoPINVOKE.new_SamlSubject(), true) {
  }

  public string dump() {
    return lassoPINVOKE.SamlSubject_dump(swigCPtr);
  }

}

}
