/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class SamlSubjectConfirmation : Node, IDisposable {
  internal SamlSubjectConfirmation(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static IntPtr getCPtr(SamlSubjectConfirmation obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  ~SamlSubjectConfirmation() {
    Dispose();
  }

  public virtual void Dispose() {
  base.Dispose();
}

  public string subjectConfirmationData {
    set {
      lassoPINVOKE.set_SamlSubjectConfirmation_subjectConfirmationData(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlSubjectConfirmation_subjectConfirmationData(swigCPtr);
    } 
  }

  public StringList confirmationMethod {
    set {
      lassoPINVOKE.set_SamlSubjectConfirmation_confirmationMethod(swigCPtr, StringList.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlSubjectConfirmation_confirmationMethod(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new StringList(cPtr, false);
    } 
  }

  public SamlSubjectConfirmation() : this(lassoPINVOKE.new_SamlSubjectConfirmation(), true) {
  }

  public string dump() {
    return lassoPINVOKE.SamlSubjectConfirmation_dump(swigCPtr);
  }

}

}
