/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class SamlpRequestAbstract : Node, IDisposable {
  internal SamlpRequestAbstract(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static IntPtr getCPtr(SamlpRequestAbstract obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected SamlpRequestAbstract() : this(IntPtr.Zero, false) {
  }

  public virtual void Dispose() {
  base.Dispose();
}

  public string certificateFile {
    set {
      lassoPINVOKE.set_SamlpRequestAbstract_certificateFile(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlpRequestAbstract_certificateFile(swigCPtr);
    } 
  }

  public string issueInstant {
    set {
      lassoPINVOKE.set_SamlpRequestAbstract_issueInstant(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlpRequestAbstract_issueInstant(swigCPtr);
    } 
  }

  public int majorVersion {
    set {
      lassoPINVOKE.set_SamlpRequestAbstract_majorVersion(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlpRequestAbstract_majorVersion(swigCPtr);
    } 
  }

  public int minorVersion {
    set {
      lassoPINVOKE.set_SamlpRequestAbstract_minorVersion(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlpRequestAbstract_minorVersion(swigCPtr);
    } 
  }

  public string privateKeyFile {
    set {
      lassoPINVOKE.set_SamlpRequestAbstract_privateKeyFile(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlpRequestAbstract_privateKeyFile(swigCPtr);
    } 
  }

  public string requestId {
    set {
      lassoPINVOKE.set_SamlpRequestAbstract_requestId(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_SamlpRequestAbstract_requestId(swigCPtr);
    } 
  }

  public SignatureMethod signMethod {
    set {
      lassoPINVOKE.set_SamlpRequestAbstract_signMethod(swigCPtr, (int)value);
    } 
    get {
      return (SignatureMethod)lassoPINVOKE.get_SamlpRequestAbstract_signMethod(swigCPtr);
    } 
  }

  public SWIGTYPE_p_LassoSignatureType signType {
    set {
      lassoPINVOKE.set_SamlpRequestAbstract_signType(swigCPtr, SWIGTYPE_p_LassoSignatureType.getCPtr(value));
    } 
    get {
      return new SWIGTYPE_p_LassoSignatureType(lassoPINVOKE.get_SamlpRequestAbstract_signType(swigCPtr), true);
    } 
  }

  public StringList respondWith {
    set {
      lassoPINVOKE.set_SamlpRequestAbstract_respondWith(swigCPtr, StringList.getCPtr(value));
    } 
    get {
      IntPtr cPtr = lassoPINVOKE.get_SamlpRequestAbstract_respondWith(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new StringList(cPtr, false);
    } 
  }

  public string dump() {
    return lassoPINVOKE.SamlpRequestAbstract_dump(swigCPtr);
  }

}

}
