/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

using System;

public class Server : IDisposable {
  private IntPtr swigCPtr;
  protected bool swigCMemOwn;

  internal Server(IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  internal static IntPtr getCPtr(Server obj) {
    return (obj == null) ? IntPtr.Zero : obj.swigCPtr;
  }

  protected Server() : this(IntPtr.Zero, false) {
  }

  ~Server() {
    Dispose();
  }

  public virtual void Dispose() {
    if(swigCPtr != IntPtr.Zero && swigCMemOwn) {
      swigCMemOwn = false;
      lassoPINVOKE.delete_Server(swigCPtr);
    }
    swigCPtr = IntPtr.Zero;
    GC.SuppressFinalize(this);
  }

  public string certificate {
    set {
      lassoPINVOKE.set_Server_certificate(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_Server_certificate(swigCPtr);
    } 
  }

  public string privateKey {
    set {
      lassoPINVOKE.set_Server_privateKey(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_Server_privateKey(swigCPtr);
    } 
  }

  public string privateKeyPassword {
    set {
      lassoPINVOKE.set_Server_privateKeyPassword(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_Server_privateKeyPassword(swigCPtr);
    } 
  }

  public SignatureMethod signatureMethod {
    set {
      lassoPINVOKE.set_Server_signatureMethod(swigCPtr, (int)value);
    } 
    get {
      return (SignatureMethod)lassoPINVOKE.get_Server_signatureMethod(swigCPtr);
    } 
  }

  public string caCertChain {
    set {
      lassoPINVOKE.set_Server_caCertChain(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_Server_caCertChain(swigCPtr);
    } 
  }

  public string metadataFilename {
    set {
      lassoPINVOKE.set_Server_metadataFilename(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_Server_metadataFilename(swigCPtr);
    } 
  }

  public string providerId {
    set {
      lassoPINVOKE.set_Server_providerId(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_Server_providerId(swigCPtr);
    } 
  }

  public string publicKey {
    set {
      lassoPINVOKE.set_Server_publicKey(swigCPtr, value);
    } 
    get {
      return lassoPINVOKE.get_Server_publicKey(swigCPtr);
    } 
  }

  public StringList providerIds {
    get {
      IntPtr cPtr = lassoPINVOKE.get_Server_providerIds(swigCPtr);
      return (cPtr == IntPtr.Zero) ? null : new StringList(cPtr, false);
    } 
  }

  public Server(string metadata, string privateKey, string privateKeyPassword, string certificate) : this(lassoPINVOKE.new_Server(metadata, privateKey, privateKeyPassword, certificate), true) {
  }

  public static Server newFromDump(string dump) {
    IntPtr cPtr = lassoPINVOKE.Server_newFromDump(dump);
    return (cPtr == IntPtr.Zero) ? null : new Server(cPtr, true);
  }

  public bool acceptHttpMethod(Provider remote_provider, SWIGTYPE_p_LassoMdProtocolType protocol_type, HttpMethod http_method, bool initiate_profile) {
    return lassoPINVOKE.Server_acceptHttpMethod(swigCPtr, Provider.getCPtr(remote_provider), SWIGTYPE_p_LassoMdProtocolType.getCPtr(protocol_type), (int)http_method, initiate_profile);
  }

  public string getAssertionConsumerServiceUrl(string service_id) {
    return lassoPINVOKE.Server_getAssertionConsumerServiceUrl(swigCPtr, service_id);
  }

  public string getBase64SuccinctId() {
    return lassoPINVOKE.Server_getBase64SuccinctId(swigCPtr);
  }

  public string getOrganization() {
    return lassoPINVOKE.Server_getOrganization(swigCPtr);
  }

  public HttpMethod getFirstHttpMethod(Provider remote_provider, SWIGTYPE_p_LassoMdProtocolType protocol_type) {
    return (HttpMethod)lassoPINVOKE.Server_getFirstHttpMethod(swigCPtr, Provider.getCPtr(remote_provider), SWIGTYPE_p_LassoMdProtocolType.getCPtr(protocol_type));
  }

  public string getMetadataOne(string name) {
    return lassoPINVOKE.Server_getMetadataOne(swigCPtr, name);
  }

  public bool hasProtocolProfile(SWIGTYPE_p_LassoMdProtocolType protocol_type, string protocol_profile) {
    return lassoPINVOKE.Server_hasProtocolProfile(swigCPtr, SWIGTYPE_p_LassoMdProtocolType.getCPtr(protocol_type), protocol_profile);
  }

  public int addProvider(ProviderRole role, string metadata, string publicKey, string caCertChain) {
    return lassoPINVOKE.Server_addProvider(swigCPtr, (int)role, metadata, publicKey, caCertChain);
  }

  public string dump() {
    return lassoPINVOKE.Server_dump(swigCPtr);
  }

  public Provider getProvider(string providerId) {
    IntPtr cPtr = lassoPINVOKE.Server_getProvider(swigCPtr, providerId);
    return (cPtr == IntPtr.Zero) ? null : new Provider(cPtr, false);
  }

}

}
