/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

namespace lasso {

public enum SignatureMethod {
  SIGNATURE_METHOD_RSA_SHA1 = 1,
  SIGNATURE_METHOD_DSA_SHA1
}


}
