/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;


public class AuthnRequest {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected AuthnRequest(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected AuthnRequest() {
    this(0, false);
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      throw new UnsupportedOperationException("C++ destructor does not have public access");
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(AuthnRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void setAffiliationId(String affiliationId) {
    lassoJNI.set_AuthnRequest_affiliationId(swigCPtr, affiliationId);
  }

  public String getAffiliationId() {
    return lassoJNI.get_AuthnRequest_affiliationId(swigCPtr);
  }

  public void setAssertionConsumerServiceId(String assertionConsumerServiceId) {
    lassoJNI.set_AuthnRequest_assertionConsumerServiceId(swigCPtr, assertionConsumerServiceId);
  }

  public String getAssertionConsumerServiceId() {
    return lassoJNI.get_AuthnRequest_assertionConsumerServiceId(swigCPtr);
  }

  public void setConsent(String consent) {
    lassoJNI.set_AuthnRequest_consent(swigCPtr, consent);
  }

  public String getConsent() {
    return lassoJNI.get_AuthnRequest_consent(swigCPtr);
  }

  public void setForceAuthn(boolean forceAuthn) {
    lassoJNI.set_AuthnRequest_forceAuthn(swigCPtr, forceAuthn);
  }

  public boolean getForceAuthn() {
    return lassoJNI.get_AuthnRequest_forceAuthn(swigCPtr);
  }

  public void setIsPassive(boolean isPassive) {
    lassoJNI.set_AuthnRequest_isPassive(swigCPtr, isPassive);
  }

  public boolean getIsPassive() {
    return lassoJNI.get_AuthnRequest_isPassive(swigCPtr);
  }

  public void setNameIdPolicy(String nameIdPolicy) {
    lassoJNI.set_AuthnRequest_nameIdPolicy(swigCPtr, nameIdPolicy);
  }

  public String getNameIdPolicy() {
    return lassoJNI.get_AuthnRequest_nameIdPolicy(swigCPtr);
  }

  public void setProtocolProfile(String protocolProfile) {
    lassoJNI.set_AuthnRequest_protocolProfile(swigCPtr, protocolProfile);
  }

  public String getProtocolProfile() {
    return lassoJNI.get_AuthnRequest_protocolProfile(swigCPtr);
  }

  public void setProviderId(String providerId) {
    lassoJNI.set_AuthnRequest_providerId(swigCPtr, providerId);
  }

  public String getProviderId() {
    return lassoJNI.get_AuthnRequest_providerId(swigCPtr);
  }

  public void setRelayState(String relayState) {
    lassoJNI.set_AuthnRequest_relayState(swigCPtr, relayState);
  }

  public String getRelayState() {
    return lassoJNI.get_AuthnRequest_relayState(swigCPtr);
  }

}
