/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Ecp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Ecp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Ecp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lassoJNI.delete_Ecp(swigCPtr);
    }
    swigCPtr = 0;
  }

  public String getMsgBody() {
    return lassoJNI.Ecp_msgBody_get(swigCPtr, this);
  }

  public String getMsgRelayState() {
    return lassoJNI.Ecp_msgRelayState_get(swigCPtr, this);
  }

  public String getMsgUrl() {
    return lassoJNI.Ecp_msgUrl_get(swigCPtr, this);
  }

  public void setRequest(Node value) {
    lassoJNI.Ecp_request_set(swigCPtr, this, Node.getCPtr(value), value);
  }

  public Node getRequest() {
	long cPtr = lassoJNI.Ecp_request_get(swigCPtr, this);
	return (cPtr == 0) ? null : (Node) lassoJNI.downcast_node(cPtr, null);
}

  public void setResponse(Node value) {
    lassoJNI.Ecp_response_set(swigCPtr, this, Node.getCPtr(value), value);
  }

  public Node getResponse() {
	long cPtr = lassoJNI.Ecp_response_get(swigCPtr, this);
	return (cPtr == 0) ? null : (Node) lassoJNI.downcast_node(cPtr, null);
}

  public String getAssertionConsumerURL() {
    return lassoJNI.Ecp_assertionConsumerURL_get(swigCPtr, this);
  }

  public Ecp(Server server) {
    this(lassoJNI.new_Ecp(Server.getCPtr(server), server), true);
  }

  public int processAuthnRequestMsg(String authnRequestMsg) {
    return lassoJNI.Ecp_processAuthnRequestMsg(swigCPtr, this, authnRequestMsg);
  }

  public int processResponseMsg(String responseMsg) {
    return lassoJNI.Ecp_processResponseMsg(swigCPtr, this, responseMsg);
  }

}
