/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Federation {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Federation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Federation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lassoJNI.delete_Federation(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setRemoteProviderId(String value) {
    lassoJNI.Federation_remoteProviderId_set(swigCPtr, this, value);
  }

  public String getRemoteProviderId() {
    return lassoJNI.Federation_remoteProviderId_get(swigCPtr, this);
  }

  public void setLocalNameIdentifier(Node value) {
    lassoJNI.Federation_localNameIdentifier_set(swigCPtr, this, Node.getCPtr(value), value);
  }

  public Node getLocalNameIdentifier() {
	long cPtr = lassoJNI.Federation_localNameIdentifier_get(swigCPtr, this);
	return (cPtr == 0) ? null : (Node) lassoJNI.downcast_node(cPtr, null);
}

  public void setRemoteNameIdentifier(Node value) {
    lassoJNI.Federation_remoteNameIdentifier_set(swigCPtr, this, Node.getCPtr(value), value);
  }

  public Node getRemoteNameIdentifier() {
	long cPtr = lassoJNI.Federation_remoteNameIdentifier_get(swigCPtr, this);
	return (cPtr == 0) ? null : (Node) lassoJNI.downcast_node(cPtr, null);
}

  public Federation(String remoteProviderId) {
    this(lassoJNI.new_Federation(remoteProviderId), true);
  }

  public String dump() {
    return lassoJNI.Federation_dump(swigCPtr, this);
  }

  public void buildLocalNameIdentifier(String nameQualifier, String format, String content) {
    lassoJNI.Federation_buildLocalNameIdentifier(swigCPtr, this, nameQualifier, format, content);
  }

  public boolean verifyNameIdentifier(Node nameIdentifier) {
    return lassoJNI.Federation_verifyNameIdentifier(swigCPtr, this, Node.getCPtr(nameIdentifier), nameIdentifier);
  }

}
