package com.entrouvert.lasso;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public class lasso implements lassoConstants {
  public static int init() {
    return lassoJNI.init();
  }

  public static int shutdown() {
    return lassoJNI.shutdown();
  }

  public static int getRequestTypeFromSoapMsg(String soap) {
    return lassoJNI.getRequestTypeFromSoapMsg(soap);
  }

}
