package com.entrouvert.lasso;

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */


public interface lassoConstants {
  // enums and constants
  public final static int httpMethodAny = lassoJNI.get_httpMethodAny();
  public final static int httpMethodGet = lassoJNI.get_httpMethodGet();
  public final static int httpMethodPost = lassoJNI.get_httpMethodPost();
  public final static int httpMethodRedirect = lassoJNI.get_httpMethodRedirect();
  public final static int httpMethodSoap = lassoJNI.get_httpMethodSoap();
  public final static String libConsentObtained = lassoJNI.get_libConsentObtained();
  public final static String libConsentUnavailable = lassoJNI.get_libConsentUnavailable();
  public final static String libConsentInapplicable = lassoJNI.get_libConsentInapplicable();
  public final static String libNameIdPolicyTypeNone = lassoJNI.get_libNameIdPolicyTypeNone();
  public final static String libNameIdPolicyTypeOneTime = lassoJNI.get_libNameIdPolicyTypeOneTime();
  public final static String libNameIdPolicyTypeFederated = lassoJNI.get_libNameIdPolicyTypeFederated();
  public final static String libNameIdPolicyTypeAny = lassoJNI.get_libNameIdPolicyTypeAny();
  public final static String libProtocolProfileBrwsArt = lassoJNI.get_libProtocolProfileBrwsArt();
  public final static String libProtocolProfileBrwsPost = lassoJNI.get_libProtocolProfileBrwsPost();
  public final static String libProtocolProfileFedTermIdpHttp = lassoJNI.get_libProtocolProfileFedTermIdpHttp();
  public final static String libProtocolProfileFedTermIdpSoap = lassoJNI.get_libProtocolProfileFedTermIdpSoap();
  public final static String libProtocolProfileFedTermSpHttp = lassoJNI.get_libProtocolProfileFedTermSpHttp();
  public final static String libProtocolProfileFedTermSpSoap = lassoJNI.get_libProtocolProfileFedTermSpSoap();
  public final static String libProtocolProfileRniIdpHttp = lassoJNI.get_libProtocolProfileRniIdpHttp();
  public final static String libProtocolProfileRniIdpSoap = lassoJNI.get_libProtocolProfileRniIdpSoap();
  public final static String libProtocolProfileRniSpHttp = lassoJNI.get_libProtocolProfileRniSpHttp();
  public final static String libProtocolProfileRniSpSoap = lassoJNI.get_libProtocolProfileRniSpSoap();
  public final static String libProtocolProfileSloIdpHttp = lassoJNI.get_libProtocolProfileSloIdpHttp();
  public final static String libProtocolProfileSloIdpSoap = lassoJNI.get_libProtocolProfileSloIdpSoap();
  public final static String libProtocolProfileSloSpHttp = lassoJNI.get_libProtocolProfileSloSpHttp();
  public final static String libProtocolProfileSloSpSoap = lassoJNI.get_libProtocolProfileSloSpSoap();
  public final static int loginProtocolProfileBrwsArt = lassoJNI.get_loginProtocolProfileBrwsArt();
  public final static int loginProtocolProfileBrwsPost = lassoJNI.get_loginProtocolProfileBrwsPost();
  public final static int messageTypeNone = lassoJNI.get_messageTypeNone();
  public final static int messageTypeAuthnRequest = lassoJNI.get_messageTypeAuthnRequest();
  public final static int messageTypeAuthnResponse = lassoJNI.get_messageTypeAuthnResponse();
  public final static int messageTypeRequest = lassoJNI.get_messageTypeRequest();
  public final static int messageTypeResponse = lassoJNI.get_messageTypeResponse();
  public final static int messageTypeArtifact = lassoJNI.get_messageTypeArtifact();
  public final static int providerTypeNone = lassoJNI.get_providerTypeNone();
  public final static int providerTypeSp = lassoJNI.get_providerTypeSp();
  public final static int providerTypeIdp = lassoJNI.get_providerTypeIdp();
  public final static int requestTypeInvalid = lassoJNI.get_requestTypeInvalid();
  public final static int requestTypeLogin = lassoJNI.get_requestTypeLogin();
  public final static int requestTypeLogout = lassoJNI.get_requestTypeLogout();
  public final static int requestTypeDefederation = lassoJNI.get_requestTypeDefederation();
  public final static int requestTypeRegisterNameIdentifier = lassoJNI.get_requestTypeRegisterNameIdentifier();
  public final static int requestTypeNameIdentifierMapping = lassoJNI.get_requestTypeNameIdentifierMapping();
  public final static int requestTypeLecp = lassoJNI.get_requestTypeLecp();
  public final static String samlAuthenticationMethodPassword = lassoJNI.get_samlAuthenticationMethodPassword();
  public final static String samlAuthenticationMethodKerberos = lassoJNI.get_samlAuthenticationMethodKerberos();
  public final static String samlAuthenticationMethodSecureRemotePassword = lassoJNI.get_samlAuthenticationMethodSecureRemotePassword();
  public final static String samlAuthenticationMethodHardwareToken = lassoJNI.get_samlAuthenticationMethodHardwareToken();
  public final static String samlAuthenticationMethodSmartcardPki = lassoJNI.get_samlAuthenticationMethodSmartcardPki();
  public final static String samlAuthenticationMethodSoftwarePki = lassoJNI.get_samlAuthenticationMethodSoftwarePki();
  public final static String samlAuthenticationMethodPgp = lassoJNI.get_samlAuthenticationMethodPgp();
  public final static String samlAuthenticationMethodSpki = lassoJNI.get_samlAuthenticationMethodSpki();
  public final static String samlAuthenticationMethodXkms = lassoJNI.get_samlAuthenticationMethodXkms();
  public final static String samlAuthenticationMethodXmlDsig = lassoJNI.get_samlAuthenticationMethodXmlDsig();
  public final static String samlAuthenticationMethodUnspecified = lassoJNI.get_samlAuthenticationMethodUnspecified();
  public final static int signatureMethodRsaSha1 = lassoJNI.get_signatureMethodRsaSha1();
  public final static int signatureMethodDsaSha1 = lassoJNI.get_signatureMethodDsaSha1();
  public final static int XML_ERROR_NODE_NOT_FOUND = lassoJNI.get_XML_ERROR_NODE_NOT_FOUND();
  public final static int XML_ERROR_NODE_CONTENT_NOT_FOUND = lassoJNI.get_XML_ERROR_NODE_CONTENT_NOT_FOUND();
  public final static int XML_ERROR_ATTR_NOT_FOUND = lassoJNI.get_XML_ERROR_ATTR_NOT_FOUND();
  public final static int XML_ERROR_ATTR_VALUE_NOT_FOUND = lassoJNI.get_XML_ERROR_ATTR_VALUE_NOT_FOUND();
  public final static int DS_ERROR_SIGNATURE_TMPL_CREATION_FAILED = lassoJNI.get_DS_ERROR_SIGNATURE_TMPL_CREATION_FAILED();
  public final static int DS_ERROR_CONTEXT_CREATION_FAILED = lassoJNI.get_DS_ERROR_CONTEXT_CREATION_FAILED();
  public final static int DS_ERROR_PUBLIC_KEY_LOAD_FAILED = lassoJNI.get_DS_ERROR_PUBLIC_KEY_LOAD_FAILED();
  public final static int DS_ERROR_PRIVATE_KEY_LOAD_FAILED = lassoJNI.get_DS_ERROR_PRIVATE_KEY_LOAD_FAILED();
  public final static int DS_ERROR_CERTIFICATE_LOAD_FAILED = lassoJNI.get_DS_ERROR_CERTIFICATE_LOAD_FAILED();
  public final static int DS_ERROR_SIGNATURE_FAILED = lassoJNI.get_DS_ERROR_SIGNATURE_FAILED();
  public final static int DS_ERROR_SIGNATURE_NOT_FOUND = lassoJNI.get_DS_ERROR_SIGNATURE_NOT_FOUND();
  public final static int DS_ERROR_KEYS_MNGR_CREATION_FAILED = lassoJNI.get_DS_ERROR_KEYS_MNGR_CREATION_FAILED();
  public final static int DS_ERROR_KEYS_MNGR_INIT_FAILED = lassoJNI.get_DS_ERROR_KEYS_MNGR_INIT_FAILED();
  public final static int DS_ERROR_SIGNATURE_VERIFICATION_FAILED = lassoJNI.get_DS_ERROR_SIGNATURE_VERIFICATION_FAILED();
  public final static int DS_ERROR_INVALID_SIGNATURE = lassoJNI.get_DS_ERROR_INVALID_SIGNATURE();
  public final static int SERVER_ERROR_PROVIDER_NOT_FOUND = lassoJNI.get_SERVER_ERROR_PROVIDER_NOT_FOUND();
  public final static int SERVER_ERROR_ADD_PROVIDER_FAILED = lassoJNI.get_SERVER_ERROR_ADD_PROVIDER_FAILED();
  public final static int LOGOUT_ERROR_UNSUPPORTED_PROFILE = lassoJNI.get_LOGOUT_ERROR_UNSUPPORTED_PROFILE();
  public final static int PROFILE_ERROR_INVALID_QUERY = lassoJNI.get_PROFILE_ERROR_INVALID_QUERY();
  public final static int PROFILE_ERROR_MISSING_REQUEST = lassoJNI.get_PROFILE_ERROR_MISSING_REQUEST();
  public final static int PARAM_ERROR_BADTYPE_OR_NULL_OBJ = lassoJNI.get_PARAM_ERROR_BADTYPE_OR_NULL_OBJ();
  public final static int PARAM_ERROR_INVALID_VALUE = lassoJNI.get_PARAM_ERROR_INVALID_VALUE();
  public final static int PARAM_ERROR_ERR_CHECK_FAILED = lassoJNI.get_PARAM_ERROR_ERR_CHECK_FAILED();
  public final static int ERROR_UNDEFINED = lassoJNI.get_ERROR_UNDEFINED();
}
