/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;


public class Lecp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Lecp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected Lecp() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lassoJNI.delete_Lecp(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(Lecp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public AuthnRequest getAuthnRequest() {
    long cPtr = lassoJNI.get_Lecp_authnRequest(swigCPtr);
    return (cPtr == 0) ? null : new AuthnRequest(cPtr, false);
  }

  public AuthnResponse getAuthnResponse() {
    long cPtr = lassoJNI.get_Lecp_authnResponse(swigCPtr);
    return (cPtr == 0) ? null : new AuthnResponse(cPtr, false);
  }

  public void setIdentity(Identity identity) {
    lassoJNI.set_Lecp_identity(swigCPtr, Identity.getCPtr(identity));
  }

  public Identity getIdentity() {
    long cPtr = lassoJNI.get_Lecp_identity(swigCPtr);
    return (cPtr == 0) ? null : new Identity(cPtr, false);
  }

  public boolean getIsIdentityDirty() {
    return lassoJNI.get_Lecp_isIdentityDirty(swigCPtr);
  }

  public boolean getIsSessionDirty() {
    return lassoJNI.get_Lecp_isSessionDirty(swigCPtr);
  }

  public String getMsgBody() {
    return lassoJNI.get_Lecp_msgBody(swigCPtr);
  }

  public String getMsgRelayState() {
    return lassoJNI.get_Lecp_msgRelayState(swigCPtr);
  }

  public String getMsgUrl() {
    return lassoJNI.get_Lecp_msgUrl(swigCPtr);
  }

  public String getNameIdentifier() {
    return lassoJNI.get_Lecp_nameIdentifier(swigCPtr);
  }

  public void setRemoteProviderId(String remoteProviderId) {
    lassoJNI.set_Lecp_remoteProviderId(swigCPtr, remoteProviderId);
  }

  public String getRemoteProviderId() {
    return lassoJNI.get_Lecp_remoteProviderId(swigCPtr);
  }

  public Request getRequest() {
    long cPtr = lassoJNI.get_Lecp_request(swigCPtr);
    return (cPtr == 0) ? null : new Request(cPtr, false);
  }

  public Response getResponse() {
    long cPtr = lassoJNI.get_Lecp_response(swigCPtr);
    return (cPtr == 0) ? null : new Response(cPtr, false);
  }

  public void setResponseStatus(String responseStatus) {
    lassoJNI.set_Lecp_responseStatus(swigCPtr, responseStatus);
  }

  public String getResponseStatus() {
    return lassoJNI.get_Lecp_responseStatus(swigCPtr);
  }

  public void setSession(Session session) {
    lassoJNI.set_Lecp_session(swigCPtr, Session.getCPtr(session));
  }

  public Session getSession() {
    long cPtr = lassoJNI.get_Lecp_session(swigCPtr);
    return (cPtr == 0) ? null : new Session(cPtr, false);
  }

  public Lecp(Server server) {
    this(lassoJNI.new_Lecp(Server.getCPtr(server)), true);
  }

  public void setIdentityFromDump(String dump) {
    lassoJNI.Lecp_setIdentityFromDump(swigCPtr, dump);
  }

  public void setSessionFromDump(String dump) {
    lassoJNI.Lecp_setSessionFromDump(swigCPtr, dump);
  }

  public void buildAuthnRequestEnvelopeMsg() {
    lassoJNI.Lecp_buildAuthnRequestEnvelopeMsg(swigCPtr);
  }

  public void buildAuthnRequestMsg(String remoteProviderId) {
    lassoJNI.Lecp_buildAuthnRequestMsg(swigCPtr, remoteProviderId);
  }

  public void buildAuthnResponseEnvelopeMsg(int authenticationResult, String authenticationMethod, String reauthenticateOnOrAfter) {
    lassoJNI.Lecp_buildAuthnResponseEnvelopeMsg(swigCPtr, authenticationResult, authenticationMethod, reauthenticateOnOrAfter);
  }

  public void buildAuthnResponseMsg() {
    lassoJNI.Lecp_buildAuthnResponseMsg(swigCPtr);
  }

  public void initAuthnRequest() {
    lassoJNI.Lecp_initAuthnRequest(swigCPtr);
  }

  public void initFromAuthnRequestMsg(String authnRequestMsg, int httpMethod) {
    lassoJNI.Lecp_initFromAuthnRequestMsg(swigCPtr, authnRequestMsg, httpMethod);
  }

  public void processAuthnRequestEnvelopeMsg(String requestMsg) {
    lassoJNI.Lecp_processAuthnRequestEnvelopeMsg(swigCPtr, requestMsg);
  }

  public void processAuthnResponseEnvelopeMsg(String responseMsg) {
    lassoJNI.Lecp_processAuthnResponseEnvelopeMsg(swigCPtr, responseMsg);
  }

}
