/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class LibAuthnRequest extends SamlpRequestAbstract {
  protected LibAuthnRequest(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(LibAuthnRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAffiliationId(String value) {
    lassoJNI.LibAuthnRequest_affiliationId_set(swigCPtr, this, value);
  }

  public String getAffiliationId() {
    return lassoJNI.LibAuthnRequest_affiliationId_get(swigCPtr, this);
  }

  public void setAssertionConsumerServiceId(String value) {
    lassoJNI.LibAuthnRequest_assertionConsumerServiceId_set(swigCPtr, this, value);
  }

  public String getAssertionConsumerServiceId() {
    return lassoJNI.LibAuthnRequest_assertionConsumerServiceId_get(swigCPtr, this);
  }

  public void setConsent(String value) {
    lassoJNI.LibAuthnRequest_consent_set(swigCPtr, this, value);
  }

  public String getConsent() {
    return lassoJNI.LibAuthnRequest_consent_get(swigCPtr, this);
  }

  public void setForceAuthn(boolean value) {
    lassoJNI.LibAuthnRequest_forceAuthn_set(swigCPtr, this, value);
  }

  public boolean getForceAuthn() {
    return lassoJNI.LibAuthnRequest_forceAuthn_get(swigCPtr, this);
  }

  public void setIsPassive(boolean value) {
    lassoJNI.LibAuthnRequest_isPassive_set(swigCPtr, this, value);
  }

  public boolean getIsPassive() {
    return lassoJNI.LibAuthnRequest_isPassive_get(swigCPtr, this);
  }

  public void setNameIdPolicy(String value) {
    lassoJNI.LibAuthnRequest_nameIdPolicy_set(swigCPtr, this, value);
  }

  public String getNameIdPolicy() {
    return lassoJNI.LibAuthnRequest_nameIdPolicy_get(swigCPtr, this);
  }

  public void setProtocolProfile(String value) {
    lassoJNI.LibAuthnRequest_protocolProfile_set(swigCPtr, this, value);
  }

  public String getProtocolProfile() {
    return lassoJNI.LibAuthnRequest_protocolProfile_get(swigCPtr, this);
  }

  public void setProviderId(String value) {
    lassoJNI.LibAuthnRequest_providerId_set(swigCPtr, this, value);
  }

  public String getProviderId() {
    return lassoJNI.LibAuthnRequest_providerId_get(swigCPtr, this);
  }

  public void setRelayState(String value) {
    lassoJNI.LibAuthnRequest_relayState_set(swigCPtr, this, value);
  }

  public String getRelayState() {
    return lassoJNI.LibAuthnRequest_relayState_get(swigCPtr, this);
  }

  public void setCertificateFile(String value) {
    lassoJNI.LibAuthnRequest_certificateFile_set(swigCPtr, this, value);
  }

  public String getCertificateFile() {
    return lassoJNI.LibAuthnRequest_certificateFile_get(swigCPtr, this);
  }

  public void setIssueInstant(String value) {
    lassoJNI.LibAuthnRequest_issueInstant_set(swigCPtr, this, value);
  }

  public String getIssueInstant() {
    return lassoJNI.LibAuthnRequest_issueInstant_get(swigCPtr, this);
  }

  public void setMajorVersion(int value) {
    lassoJNI.LibAuthnRequest_majorVersion_set(swigCPtr, this, value);
  }

  public int getMajorVersion() {
    return lassoJNI.LibAuthnRequest_majorVersion_get(swigCPtr, this);
  }

  public void setMinorVersion(int value) {
    lassoJNI.LibAuthnRequest_minorVersion_set(swigCPtr, this, value);
  }

  public int getMinorVersion() {
    return lassoJNI.LibAuthnRequest_minorVersion_get(swigCPtr, this);
  }

  public void setPrivateKeyFile(String value) {
    lassoJNI.LibAuthnRequest_privateKeyFile_set(swigCPtr, this, value);
  }

  public String getPrivateKeyFile() {
    return lassoJNI.LibAuthnRequest_privateKeyFile_get(swigCPtr, this);
  }

  public void setRequestId(String value) {
    lassoJNI.LibAuthnRequest_requestId_set(swigCPtr, this, value);
  }

  public String getRequestId() {
    return lassoJNI.LibAuthnRequest_requestId_get(swigCPtr, this);
  }

  public void setRespondWith(StringList value) {
    lassoJNI.LibAuthnRequest_respondWith_set(swigCPtr, this, StringList.getCPtr(value), value);
  }

  public StringList getRespondWith() {
    long cPtr = lassoJNI.LibAuthnRequest_respondWith_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setSignMethod(int value) {
    lassoJNI.LibAuthnRequest_signMethod_set(swigCPtr, this, value);
  }

  public int getSignMethod() {
    return lassoJNI.LibAuthnRequest_signMethod_get(swigCPtr, this);
  }

  public void setSignType(int value) {
    lassoJNI.LibAuthnRequest_signType_set(swigCPtr, this, value);
  }

  public int getSignType() {
    return lassoJNI.LibAuthnRequest_signType_get(swigCPtr, this);
  }

  public void setExtension(StringList value) {
    lassoJNI.LibAuthnRequest_extension_set(swigCPtr, this, StringList.getCPtr(value), value);
  }

  public StringList getExtension() {
    long cPtr = lassoJNI.LibAuthnRequest_extension_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setRequestAuthnContext(LibRequestAuthnContext value) {
    lassoJNI.LibAuthnRequest_requestAuthnContext_set(swigCPtr, this, LibRequestAuthnContext.getCPtr(value), value);
  }

  public LibRequestAuthnContext getRequestAuthnContext() {
    long cPtr = lassoJNI.LibAuthnRequest_requestAuthnContext_get(swigCPtr, this);
    return (cPtr == 0) ? null : new LibRequestAuthnContext(cPtr, false);
  }

  public LibAuthnRequest() {
    this(lassoJNI.new_LibAuthnRequest(), true);
  }

  public String dump() {
    return lassoJNI.LibAuthnRequest_dump(swigCPtr, this);
  }

}
