/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class LibRegisterNameIdentifierResponse extends LibStatusResponse {
  protected LibRegisterNameIdentifierResponse(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(LibRegisterNameIdentifierResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setExtension(StringList Extension) {
    lassoJNI.set_LibRegisterNameIdentifierResponse_extension(swigCPtr, StringList.getCPtr(Extension));
  }

  public StringList getExtension() {
    long cPtr = lassoJNI.get_LibRegisterNameIdentifierResponse_extension(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setProviderId(String ProviderID) {
    lassoJNI.set_LibRegisterNameIdentifierResponse_providerId(swigCPtr, ProviderID);
  }

  public String getProviderId() {
    return lassoJNI.get_LibRegisterNameIdentifierResponse_providerId(swigCPtr);
  }

  public void setRelayState(String RelayState) {
    lassoJNI.set_LibRegisterNameIdentifierResponse_relayState(swigCPtr, RelayState);
  }

  public String getRelayState() {
    return lassoJNI.get_LibRegisterNameIdentifierResponse_relayState(swigCPtr);
  }

  public void setStatus(SamlpStatus Status) {
    lassoJNI.set_LibRegisterNameIdentifierResponse_status(swigCPtr, SamlpStatus.getCPtr(Status));
  }

  public SamlpStatus getStatus() {
    long cPtr = lassoJNI.get_LibRegisterNameIdentifierResponse_status(swigCPtr);
    return (cPtr == 0) ? null : new SamlpStatus(cPtr, false);
  }

  public LibRegisterNameIdentifierResponse() {
    this(lassoJNI.new_LibRegisterNameIdentifierResponse(), true);
  }

  public static LibRegisterNameIdentifierResponse newFull(String providerID, String statusCodeValue, LibRegisterNameIdentifierRequest request, SWIGTYPE_p_LassoSignatureType sign_type, int sign_method) {
    long cPtr = lassoJNI.LibRegisterNameIdentifierResponse_newFull(providerID, statusCodeValue, LibRegisterNameIdentifierRequest.getCPtr(request), SWIGTYPE_p_LassoSignatureType.getCPtr(sign_type), sign_method);
    return (cPtr == 0) ? null : new LibRegisterNameIdentifierResponse(cPtr, true);
  }

  public String dump() {
    return lassoJNI.LibRegisterNameIdentifierResponse_dump(swigCPtr);
  }

}
