/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class LibRegisterNameIdentifierResponse extends LibStatusResponse {
  protected LibRegisterNameIdentifierResponse(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(LibRegisterNameIdentifierResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setExtension(StringList value) {
    lassoJNI.LibRegisterNameIdentifierResponse_extension_set(swigCPtr, StringList.getCPtr(value));
  }

  public StringList getExtension() {
    long cPtr = lassoJNI.LibRegisterNameIdentifierResponse_extension_get(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setProviderId(String value) {
    lassoJNI.LibRegisterNameIdentifierResponse_providerId_set(swigCPtr, value);
  }

  public String getProviderId() {
    return lassoJNI.LibRegisterNameIdentifierResponse_providerId_get(swigCPtr);
  }

  public void setRelayState(String value) {
    lassoJNI.LibRegisterNameIdentifierResponse_relayState_set(swigCPtr, value);
  }

  public String getRelayState() {
    return lassoJNI.LibRegisterNameIdentifierResponse_relayState_get(swigCPtr);
  }

  public void setStatus(SamlpStatus value) {
    lassoJNI.LibRegisterNameIdentifierResponse_status_set(swigCPtr, SamlpStatus.getCPtr(value));
  }

  public SamlpStatus getStatus() {
    long cPtr = lassoJNI.LibRegisterNameIdentifierResponse_status_get(swigCPtr);
    return (cPtr == 0) ? null : new SamlpStatus(cPtr, false);
  }

  public LibRegisterNameIdentifierResponse() {
    this(lassoJNI.new_LibRegisterNameIdentifierResponse(), true);
  }

  public static LibRegisterNameIdentifierResponse newFull(String providerID, String statusCodeValue, LibRegisterNameIdentifierRequest request, SWIGTYPE_p_LassoSignatureType sign_type, int sign_method) {
    long cPtr = lassoJNI.LibRegisterNameIdentifierResponse_newFull(providerID, statusCodeValue, LibRegisterNameIdentifierRequest.getCPtr(request), SWIGTYPE_p_LassoSignatureType.getCPtr(sign_type), sign_method);
    return (cPtr == 0) ? null : new LibRegisterNameIdentifierResponse(cPtr, true);
  }

  public String dump() {
    return lassoJNI.LibRegisterNameIdentifierResponse_dump(swigCPtr);
  }

}
