/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class LibRegisterNameIdentifierRequest extends SamlpRequestAbstract {
  protected LibRegisterNameIdentifierRequest(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(LibRegisterNameIdentifierRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setProviderId(String value) {
    lassoJNI.LibRegisterNameIdentifierRequest_providerId_set(swigCPtr, this, value);
  }

  public String getProviderId() {
    return lassoJNI.LibRegisterNameIdentifierRequest_providerId_get(swigCPtr, this);
  }

  public void setRelayState(String value) {
    lassoJNI.LibRegisterNameIdentifierRequest_relayState_set(swigCPtr, this, value);
  }

  public String getRelayState() {
    return lassoJNI.LibRegisterNameIdentifierRequest_relayState_get(swigCPtr, this);
  }

  public void setCertificateFile(String value) {
    lassoJNI.LibRegisterNameIdentifierRequest_certificateFile_set(swigCPtr, this, value);
  }

  public String getCertificateFile() {
    return lassoJNI.LibRegisterNameIdentifierRequest_certificateFile_get(swigCPtr, this);
  }

  public void setIssueInstant(String value) {
    lassoJNI.LibRegisterNameIdentifierRequest_issueInstant_set(swigCPtr, this, value);
  }

  public String getIssueInstant() {
    return lassoJNI.LibRegisterNameIdentifierRequest_issueInstant_get(swigCPtr, this);
  }

  public void setMajorVersion(int value) {
    lassoJNI.LibRegisterNameIdentifierRequest_majorVersion_set(swigCPtr, this, value);
  }

  public int getMajorVersion() {
    return lassoJNI.LibRegisterNameIdentifierRequest_majorVersion_get(swigCPtr, this);
  }

  public void setMinorVersion(int value) {
    lassoJNI.LibRegisterNameIdentifierRequest_minorVersion_set(swigCPtr, this, value);
  }

  public int getMinorVersion() {
    return lassoJNI.LibRegisterNameIdentifierRequest_minorVersion_get(swigCPtr, this);
  }

  public void setPrivateKeyFile(String value) {
    lassoJNI.LibRegisterNameIdentifierRequest_privateKeyFile_set(swigCPtr, this, value);
  }

  public String getPrivateKeyFile() {
    return lassoJNI.LibRegisterNameIdentifierRequest_privateKeyFile_get(swigCPtr, this);
  }

  public void setRequestId(String value) {
    lassoJNI.LibRegisterNameIdentifierRequest_requestId_set(swigCPtr, this, value);
  }

  public String getRequestId() {
    return lassoJNI.LibRegisterNameIdentifierRequest_requestId_get(swigCPtr, this);
  }

  public void setRespondWith(StringList value) {
    lassoJNI.LibRegisterNameIdentifierRequest_respondWith_set(swigCPtr, this, StringList.getCPtr(value), value);
  }

  public StringList getRespondWith() {
    long cPtr = lassoJNI.LibRegisterNameIdentifierRequest_respondWith_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setSignMethod(int value) {
    lassoJNI.LibRegisterNameIdentifierRequest_signMethod_set(swigCPtr, this, value);
  }

  public int getSignMethod() {
    return lassoJNI.LibRegisterNameIdentifierRequest_signMethod_get(swigCPtr, this);
  }

  public void setSignType(int value) {
    lassoJNI.LibRegisterNameIdentifierRequest_signType_set(swigCPtr, this, value);
  }

  public int getSignType() {
    return lassoJNI.LibRegisterNameIdentifierRequest_signType_get(swigCPtr, this);
  }

  public void setExtension(StringList value) {
    lassoJNI.LibRegisterNameIdentifierRequest_extension_set(swigCPtr, this, StringList.getCPtr(value), value);
  }

  public StringList getExtension() {
    long cPtr = lassoJNI.LibRegisterNameIdentifierRequest_extension_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setIdpProvidedNameIdentifier(SamlNameIdentifier value) {
    lassoJNI.LibRegisterNameIdentifierRequest_idpProvidedNameIdentifier_set(swigCPtr, this, SamlNameIdentifier.getCPtr(value), value);
  }

  public SamlNameIdentifier getIdpProvidedNameIdentifier() {
    long cPtr = lassoJNI.LibRegisterNameIdentifierRequest_idpProvidedNameIdentifier_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SamlNameIdentifier(cPtr, false);
  }

  public void setOldProvidedNameIdentifier(SamlNameIdentifier value) {
    lassoJNI.LibRegisterNameIdentifierRequest_oldProvidedNameIdentifier_set(swigCPtr, this, SamlNameIdentifier.getCPtr(value), value);
  }

  public SamlNameIdentifier getOldProvidedNameIdentifier() {
    long cPtr = lassoJNI.LibRegisterNameIdentifierRequest_oldProvidedNameIdentifier_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SamlNameIdentifier(cPtr, false);
  }

  public void setSpProvidedNameIdentifier(SamlNameIdentifier value) {
    lassoJNI.LibRegisterNameIdentifierRequest_spProvidedNameIdentifier_set(swigCPtr, this, SamlNameIdentifier.getCPtr(value), value);
  }

  public SamlNameIdentifier getSpProvidedNameIdentifier() {
    long cPtr = lassoJNI.LibRegisterNameIdentifierRequest_spProvidedNameIdentifier_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SamlNameIdentifier(cPtr, false);
  }

  public LibRegisterNameIdentifierRequest() {
    this(lassoJNI.new_LibRegisterNameIdentifierRequest(), true);
  }

  public static LibRegisterNameIdentifierRequest newFull(String providerID, SamlNameIdentifier idpNameIdentifier, SamlNameIdentifier spNameIdentifier, SamlNameIdentifier oldNameIdentifier, int sign_type, int sign_method) {
    long cPtr = lassoJNI.LibRegisterNameIdentifierRequest_newFull(providerID, SamlNameIdentifier.getCPtr(idpNameIdentifier), idpNameIdentifier, SamlNameIdentifier.getCPtr(spNameIdentifier), spNameIdentifier, SamlNameIdentifier.getCPtr(oldNameIdentifier), oldNameIdentifier, sign_type, sign_method);
    return (cPtr == 0) ? null : new LibRegisterNameIdentifierRequest(cPtr, true);
  }

  public String dump() {
    return lassoJNI.LibRegisterNameIdentifierRequest_dump(swigCPtr, this);
  }

}
