/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class LibRegisterNameIdentifierRequest extends SamlpRequestAbstract {
  protected LibRegisterNameIdentifierRequest(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(LibRegisterNameIdentifierRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setProviderId(String ProviderID) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_providerId(swigCPtr, ProviderID);
  }

  public String getProviderId() {
    return lassoJNI.get_LibRegisterNameIdentifierRequest_providerId(swigCPtr);
  }

  public void setRelayState(String RelayState) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_relayState(swigCPtr, RelayState);
  }

  public String getRelayState() {
    return lassoJNI.get_LibRegisterNameIdentifierRequest_relayState(swigCPtr);
  }

  public void setCertificateFile(String certificate_file) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_certificateFile(swigCPtr, certificate_file);
  }

  public String getCertificateFile() {
    return lassoJNI.get_LibRegisterNameIdentifierRequest_certificateFile(swigCPtr);
  }

  public void setIssueInstant(String IssueInstant) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_issueInstant(swigCPtr, IssueInstant);
  }

  public String getIssueInstant() {
    return lassoJNI.get_LibRegisterNameIdentifierRequest_issueInstant(swigCPtr);
  }

  public void setMajorVersion(int MajorVersion) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_majorVersion(swigCPtr, MajorVersion);
  }

  public int getMajorVersion() {
    return lassoJNI.get_LibRegisterNameIdentifierRequest_majorVersion(swigCPtr);
  }

  public void setMinorVersion(int MinorVersion) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_minorVersion(swigCPtr, MinorVersion);
  }

  public int getMinorVersion() {
    return lassoJNI.get_LibRegisterNameIdentifierRequest_minorVersion(swigCPtr);
  }

  public void setPrivateKeyFile(String private_key_file) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_privateKeyFile(swigCPtr, private_key_file);
  }

  public String getPrivateKeyFile() {
    return lassoJNI.get_LibRegisterNameIdentifierRequest_privateKeyFile(swigCPtr);
  }

  public void setRequestId(String RequestID) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_requestId(swigCPtr, RequestID);
  }

  public String getRequestId() {
    return lassoJNI.get_LibRegisterNameIdentifierRequest_requestId(swigCPtr);
  }

  public void setRespondWith(StringList RespondWith) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_respondWith(swigCPtr, StringList.getCPtr(RespondWith));
  }

  public StringList getRespondWith() {
    long cPtr = lassoJNI.get_LibRegisterNameIdentifierRequest_respondWith(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setSignMethod(int sign_method) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_signMethod(swigCPtr, sign_method);
  }

  public int getSignMethod() {
    return lassoJNI.get_LibRegisterNameIdentifierRequest_signMethod(swigCPtr);
  }

  public void setSignType(SWIGTYPE_p_LassoSignatureType sign_type) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_signType(swigCPtr, SWIGTYPE_p_LassoSignatureType.getCPtr(sign_type));
  }

  public SWIGTYPE_p_LassoSignatureType getSignType() {
    return new SWIGTYPE_p_LassoSignatureType(lassoJNI.get_LibRegisterNameIdentifierRequest_signType(swigCPtr), true);
  }

  public void setExtension(StringList Extension) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_extension(swigCPtr, StringList.getCPtr(Extension));
  }

  public StringList getExtension() {
    long cPtr = lassoJNI.get_LibRegisterNameIdentifierRequest_extension(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setIdpProvidedNameIdentifier(SamlNameIdentifier IDPProvidedNameIdentifier) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_idpProvidedNameIdentifier(swigCPtr, SamlNameIdentifier.getCPtr(IDPProvidedNameIdentifier));
  }

  public SamlNameIdentifier getIdpProvidedNameIdentifier() {
    long cPtr = lassoJNI.get_LibRegisterNameIdentifierRequest_idpProvidedNameIdentifier(swigCPtr);
    return (cPtr == 0) ? null : new SamlNameIdentifier(cPtr, false);
  }

  public void setOldProvidedNameIdentifier(SamlNameIdentifier OldProvidedNameIdentifier) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_oldProvidedNameIdentifier(swigCPtr, SamlNameIdentifier.getCPtr(OldProvidedNameIdentifier));
  }

  public SamlNameIdentifier getOldProvidedNameIdentifier() {
    long cPtr = lassoJNI.get_LibRegisterNameIdentifierRequest_oldProvidedNameIdentifier(swigCPtr);
    return (cPtr == 0) ? null : new SamlNameIdentifier(cPtr, false);
  }

  public void setSpProvidedNameIdentifier(SamlNameIdentifier SPProvidedNameIdentifier) {
    lassoJNI.set_LibRegisterNameIdentifierRequest_spProvidedNameIdentifier(swigCPtr, SamlNameIdentifier.getCPtr(SPProvidedNameIdentifier));
  }

  public SamlNameIdentifier getSpProvidedNameIdentifier() {
    long cPtr = lassoJNI.get_LibRegisterNameIdentifierRequest_spProvidedNameIdentifier(swigCPtr);
    return (cPtr == 0) ? null : new SamlNameIdentifier(cPtr, false);
  }

  public LibRegisterNameIdentifierRequest() {
    this(lassoJNI.new_LibRegisterNameIdentifierRequest(), true);
  }

  public static LibRegisterNameIdentifierRequest newFull(String providerID, SamlNameIdentifier idpNameIdentifier, SamlNameIdentifier spNameIdentifier, SamlNameIdentifier oldNameIdentifier, SWIGTYPE_p_LassoSignatureType sign_type, int sign_method) {
    long cPtr = lassoJNI.LibRegisterNameIdentifierRequest_newFull(providerID, SamlNameIdentifier.getCPtr(idpNameIdentifier), SamlNameIdentifier.getCPtr(spNameIdentifier), SamlNameIdentifier.getCPtr(oldNameIdentifier), SWIGTYPE_p_LassoSignatureType.getCPtr(sign_type), sign_method);
    return (cPtr == 0) ? null : new LibRegisterNameIdentifierRequest(cPtr, true);
  }

  public String dump() {
    return lassoJNI.LibRegisterNameIdentifierRequest_dump(swigCPtr);
  }

}
