/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class LibRequestAuthnContext extends Node {
  protected LibRequestAuthnContext(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(LibRequestAuthnContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAuthnContextComparison(String AuthnContextComparison) {
    lassoJNI.set_LibRequestAuthnContext_authnContextComparison(swigCPtr, AuthnContextComparison);
  }

  public String getAuthnContextComparison() {
    return lassoJNI.get_LibRequestAuthnContext_authnContextComparison(swigCPtr);
  }

  public void setAuthnContextClassRef(StringList authnContextClassRef) {
    lassoJNI.set_LibRequestAuthnContext_authnContextClassRef(swigCPtr, StringList.getCPtr(authnContextClassRef));
  }

  public StringList getAuthnContextClassRef() {
    long cPtr = lassoJNI.get_LibRequestAuthnContext_authnContextClassRef(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setAuthnContextStatementRef(StringList authnContextStatementRef) {
    lassoJNI.set_LibRequestAuthnContext_authnContextStatementRef(swigCPtr, StringList.getCPtr(authnContextStatementRef));
  }

  public StringList getAuthnContextStatementRef() {
    long cPtr = lassoJNI.get_LibRequestAuthnContext_authnContextStatementRef(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public LibRequestAuthnContext() {
    this(lassoJNI.new_LibRequestAuthnContext(), true);
  }

  public String dump() {
    return lassoJNI.LibRequestAuthnContext_dump(swigCPtr);
  }

}
