/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class LibStatusResponse extends SamlpResponseAbstract {
  protected LibStatusResponse(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(LibStatusResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setProviderId(String ProviderID) {
    lassoJNI.set_LibStatusResponse_providerId(swigCPtr, ProviderID);
  }

  public String getProviderId() {
    return lassoJNI.get_LibStatusResponse_providerId(swigCPtr);
  }

  public void setRelayState(String RelayState) {
    lassoJNI.set_LibStatusResponse_relayState(swigCPtr, RelayState);
  }

  public String getRelayState() {
    return lassoJNI.get_LibStatusResponse_relayState(swigCPtr);
  }

  public void setExtension(StringList Extension) {
    lassoJNI.set_LibStatusResponse_extension(swigCPtr, StringList.getCPtr(Extension));
  }

  public StringList getExtension() {
    long cPtr = lassoJNI.get_LibStatusResponse_extension(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setStatus(SamlpStatus Status) {
    lassoJNI.set_LibStatusResponse_status(swigCPtr, SamlpStatus.getCPtr(Status));
  }

  public SamlpStatus getStatus() {
    long cPtr = lassoJNI.get_LibStatusResponse_status(swigCPtr);
    return (cPtr == 0) ? null : new SamlpStatus(cPtr, false);
  }

  public LibStatusResponse() {
    this(lassoJNI.new_LibStatusResponse(), true);
  }

  public String dump() {
    return lassoJNI.LibStatusResponse_dump(swigCPtr);
  }

}
