/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Login {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Login(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Login obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected Login() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lassoJNI.delete_Login(swigCPtr);
    }
    swigCPtr = 0;
  }

  public String getAssertionArtifact() {
    return lassoJNI.get_Login_assertionArtifact(swigCPtr);
  }

  public int getProtocolProfile() {
    return lassoJNI.get_Login_protocolProfile(swigCPtr);
  }

  public void setIdentity(Identity identity) {
    lassoJNI.set_Login_identity(swigCPtr, Identity.getCPtr(identity));
  }

  public Identity getIdentity() {
    long cPtr = lassoJNI.get_Login_identity(swigCPtr);
    return (cPtr == 0) ? null : new Identity(cPtr, false);
  }

  public boolean getIsIdentityDirty() {
    return lassoJNI.get_Login_isIdentityDirty(swigCPtr);
  }

  public boolean getIsSessionDirty() {
    return lassoJNI.get_Login_isSessionDirty(swigCPtr);
  }

  public String getMsgBody() {
    return lassoJNI.get_Login_msgBody(swigCPtr);
  }

  public String getMsgRelayState() {
    return lassoJNI.get_Login_msgRelayState(swigCPtr);
  }

  public String getMsgUrl() {
    return lassoJNI.get_Login_msgUrl(swigCPtr);
  }

  public void setNameIdentifier(SamlNameIdentifier nameIdentifier) {
    lassoJNI.set_Login_nameIdentifier(swigCPtr, SamlNameIdentifier.getCPtr(nameIdentifier));
  }

  public SamlNameIdentifier getNameIdentifier() {
    long cPtr = lassoJNI.get_Login_nameIdentifier(swigCPtr);
    return (cPtr == 0) ? null : new SamlNameIdentifier(cPtr, false);
  }

  public void setRemoteProviderId(String remoteProviderId) {
    lassoJNI.set_Login_remoteProviderId(swigCPtr, remoteProviderId);
  }

  public String getRemoteProviderId() {
    return lassoJNI.get_Login_remoteProviderId(swigCPtr);
  }

  public void setRequest(SamlpRequestAbstract request) {
    lassoJNI.set_Login_request(swigCPtr, SamlpRequestAbstract.getCPtr(request));
  }

  public SamlpRequestAbstract getRequest() {
	long cPtr = lassoJNI.get_Login_request(swigCPtr);
	return (cPtr == 0) ? null : (SamlpRequestAbstract) lassoJNI.downcast_node(cPtr);
}

  public void setResponse(SamlpResponseAbstract response) {
    lassoJNI.set_Login_response(swigCPtr, SamlpResponseAbstract.getCPtr(response));
  }

  public SamlpResponseAbstract getResponse() {
	long cPtr = lassoJNI.get_Login_response(swigCPtr);
	return (cPtr == 0) ? null : (SamlpResponseAbstract) lassoJNI.downcast_node(cPtr);
}

  public void setServer(Server server) {
    lassoJNI.set_Login_server(swigCPtr, Server.getCPtr(server));
  }

  public Server getServer() {
    long cPtr = lassoJNI.get_Login_server(swigCPtr);
    return (cPtr == 0) ? null : new Server(cPtr, false);
  }

  public void setSession(Session session) {
    lassoJNI.set_Login_session(swigCPtr, Session.getCPtr(session));
  }

  public Session getSession() {
    long cPtr = lassoJNI.get_Login_session(swigCPtr);
    return (cPtr == 0) ? null : new Session(cPtr, false);
  }

  public Login(Server server) {
    this(lassoJNI.new_Login(Server.getCPtr(server)), true);
  }

  public static Login newFromDump(Server server, String dump) {
    long cPtr = lassoJNI.Login_newFromDump(Server.getCPtr(server), dump);
    return (cPtr == 0) ? null : new Login(cPtr, true);
  }

  public int setIdentityFromDump(String dump) {
    return lassoJNI.Login_setIdentityFromDump(swigCPtr, dump);
  }

  public int setSessionFromDump(String dump) {
    return lassoJNI.Login_setSessionFromDump(swigCPtr, dump);
  }

  public int acceptSso() {
    return lassoJNI.Login_acceptSso(swigCPtr);
  }

  public int buildArtifactMsg(int httpMethod) {
    return lassoJNI.Login_buildArtifactMsg(swigCPtr, httpMethod);
  }

  public int buildAssertion(String authenticationMethod, String authenticationInstant, String reauthenticateOnOrAfter, String notBefore, String notOnOrAfter) {
    return lassoJNI.Login_buildAssertion(swigCPtr, authenticationMethod, authenticationInstant, reauthenticateOnOrAfter, notBefore, notOnOrAfter);
  }

  public int buildAuthnRequestMsg() {
    return lassoJNI.Login_buildAuthnRequestMsg(swigCPtr);
  }

  public int buildAuthnResponseMsg() {
    return lassoJNI.Login_buildAuthnResponseMsg(swigCPtr);
  }

  public int buildRequestMsg() {
    return lassoJNI.Login_buildRequestMsg(swigCPtr);
  }

  public int buildResponseMsg(String remoteProviderId) {
    return lassoJNI.Login_buildResponseMsg(swigCPtr, remoteProviderId);
  }

  public String dump() {
    return lassoJNI.Login_dump(swigCPtr);
  }

  public int initAuthnRequest(String remoteProviderId, int httpMethod) {
    return lassoJNI.Login_initAuthnRequest(swigCPtr, remoteProviderId, httpMethod);
  }

  public int initRequest(String responseMsg, int httpMethod) {
    return lassoJNI.Login_initRequest(swigCPtr, responseMsg, httpMethod);
  }

  public int initIdpInitiatedAuthnRequest(String remoteProviderID) {
    return lassoJNI.Login_initIdpInitiatedAuthnRequest(swigCPtr, remoteProviderID);
  }

  public boolean mustAskForConsent() {
    return lassoJNI.Login_mustAskForConsent(swigCPtr);
  }

  public boolean mustAuthenticate() {
    return lassoJNI.Login_mustAuthenticate(swigCPtr);
  }

  public int processAuthnRequestMsg(String authnrequestMsg) {
    return lassoJNI.Login_processAuthnRequestMsg(swigCPtr, authnrequestMsg);
  }

  public int processAuthnResponseMsg(String authnResponseMsg) {
    return lassoJNI.Login_processAuthnResponseMsg(swigCPtr, authnResponseMsg);
  }

  public int processRequestMsg(String requestMsg) {
    return lassoJNI.Login_processRequestMsg(swigCPtr, requestMsg);
  }

  public int processResponseMsg(String responseMsg) {
    return lassoJNI.Login_processResponseMsg(swigCPtr, responseMsg);
  }

  public int setResourceId(String content) {
    return lassoJNI.Login_setResourceId(swigCPtr, content);
  }

  public int validateRequestMsg(boolean authenticationResult, boolean isConsentObtained) {
    return lassoJNI.Login_validateRequestMsg(swigCPtr, authenticationResult, isConsentObtained);
  }

}
