/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class NameIdentifierMapping {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NameIdentifierMapping(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NameIdentifierMapping obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lassoJNI.delete_NameIdentifierMapping(swigCPtr);
    }
    swigCPtr = 0;
  }

  public String getTargetNameIdentifier() {
    return lassoJNI.NameIdentifierMapping_targetNameIdentifier_get(swigCPtr, this);
  }

  public String getArtifact() {
    return lassoJNI.NameIdentifierMapping_artifact_get(swigCPtr, this);
  }

  public void setArtifactMessage(String value) {
    lassoJNI.NameIdentifierMapping_artifactMessage_set(swigCPtr, this, value);
  }

  public String getArtifactMessage() {
    return lassoJNI.NameIdentifierMapping_artifactMessage_get(swigCPtr, this);
  }

  public void setIdentity(Identity value) {
    lassoJNI.NameIdentifierMapping_identity_set(swigCPtr, this, Identity.getCPtr(value), value);
  }

  public Identity getIdentity() {
    long cPtr = lassoJNI.NameIdentifierMapping_identity_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Identity(cPtr, false);
  }

  public boolean getIsIdentityDirty() {
    return lassoJNI.NameIdentifierMapping_isIdentityDirty_get(swigCPtr, this);
  }

  public boolean getIsSessionDirty() {
    return lassoJNI.NameIdentifierMapping_isSessionDirty_get(swigCPtr, this);
  }

  public String getMsgBody() {
    return lassoJNI.NameIdentifierMapping_msgBody_get(swigCPtr, this);
  }

  public String getMsgUrl() {
    return lassoJNI.NameIdentifierMapping_msgUrl_get(swigCPtr, this);
  }

  public void setNameIdentifier(Node value) {
    lassoJNI.NameIdentifierMapping_nameIdentifier_set(swigCPtr, this, Node.getCPtr(value), value);
  }

  public Node getNameIdentifier() {
	long cPtr = lassoJNI.NameIdentifierMapping_nameIdentifier_get(swigCPtr, this);
	return (cPtr == 0) ? null : (Node) lassoJNI.downcast_node(cPtr, null);
}

  public void setRemoteProviderId(String value) {
    lassoJNI.NameIdentifierMapping_remoteProviderId_set(swigCPtr, this, value);
  }

  public String getRemoteProviderId() {
    return lassoJNI.NameIdentifierMapping_remoteProviderId_get(swigCPtr, this);
  }

  public void setRequest(Node value) {
    lassoJNI.NameIdentifierMapping_request_set(swigCPtr, this, Node.getCPtr(value), value);
  }

  public Node getRequest() {
	long cPtr = lassoJNI.NameIdentifierMapping_request_get(swigCPtr, this);
	return (cPtr == 0) ? null : (Node) lassoJNI.downcast_node(cPtr, null);
}

  public void setResponse(Node value) {
    lassoJNI.NameIdentifierMapping_response_set(swigCPtr, this, Node.getCPtr(value), value);
  }

  public Node getResponse() {
	long cPtr = lassoJNI.NameIdentifierMapping_response_get(swigCPtr, this);
	return (cPtr == 0) ? null : (Node) lassoJNI.downcast_node(cPtr, null);
}

  public void setServer(Server value) {
    lassoJNI.NameIdentifierMapping_server_set(swigCPtr, this, Server.getCPtr(value), value);
  }

  public Server getServer() {
    long cPtr = lassoJNI.NameIdentifierMapping_server_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Server(cPtr, false);
  }

  public void setSession(Session value) {
    lassoJNI.NameIdentifierMapping_session_set(swigCPtr, this, Session.getCPtr(value), value);
  }

  public Session getSession() {
    long cPtr = lassoJNI.NameIdentifierMapping_session_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Session(cPtr, false);
  }

  public NameIdentifierMapping(Server server) {
    this(lassoJNI.new_NameIdentifierMapping(Server.getCPtr(server), server), true);
  }

  public int setIdentityFromDump(String dump) {
    return lassoJNI.NameIdentifierMapping_setIdentityFromDump(swigCPtr, this, dump);
  }

  public int setSessionFromDump(String dump) {
    return lassoJNI.NameIdentifierMapping_setSessionFromDump(swigCPtr, this, dump);
  }

  public int buildRequestMsg() {
    return lassoJNI.NameIdentifierMapping_buildRequestMsg(swigCPtr, this);
  }

  public int buildResponseMsg() {
    return lassoJNI.NameIdentifierMapping_buildResponseMsg(swigCPtr, this);
  }

  public int initRequest(String targetNamespace, String remoteProviderId) {
    return lassoJNI.NameIdentifierMapping_initRequest(swigCPtr, this, targetNamespace, remoteProviderId);
  }

  public int processRequestMsg(String requestMsg) {
    return lassoJNI.NameIdentifierMapping_processRequestMsg(swigCPtr, this, requestMsg);
  }

  public int processResponseMsg(String responseMsg) {
    return lassoJNI.NameIdentifierMapping_processResponseMsg(swigCPtr, this, responseMsg);
  }

  public int validateRequest() {
    return lassoJNI.NameIdentifierMapping_validateRequest(swigCPtr, this);
  }

}
