/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Provider {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Provider(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Provider obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lassoJNI.delete_Provider(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setCaCertChain(String value) {
    lassoJNI.Provider_caCertChain_set(swigCPtr, this, value);
  }

  public String getCaCertChain() {
    return lassoJNI.Provider_caCertChain_get(swigCPtr, this);
  }

  public void setMetadataFilename(String value) {
    lassoJNI.Provider_metadataFilename_set(swigCPtr, this, value);
  }

  public String getMetadataFilename() {
    return lassoJNI.Provider_metadataFilename_get(swigCPtr, this);
  }

  public void setProviderId(String value) {
    lassoJNI.Provider_providerId_set(swigCPtr, this, value);
  }

  public String getProviderId() {
    return lassoJNI.Provider_providerId_get(swigCPtr, this);
  }

  public void setPublicKey(String value) {
    lassoJNI.Provider_publicKey_set(swigCPtr, this, value);
  }

  public String getPublicKey() {
    return lassoJNI.Provider_publicKey_get(swigCPtr, this);
  }

  public void setRole(int value) {
    lassoJNI.Provider_role_set(swigCPtr, this, value);
  }

  public int getRole() {
    return lassoJNI.Provider_role_get(swigCPtr, this);
  }

  public Provider(int role, String metadata, String public_key, String ca_cert_chain) {
    this(lassoJNI.new_Provider(role, metadata, public_key, ca_cert_chain), true);
  }

  public static Provider newFromDump(String dump) {
    long cPtr = lassoJNI.Provider_newFromDump(dump);
    return (cPtr == 0) ? null : new Provider(cPtr, true);
  }

  public String dump() {
    return lassoJNI.Provider_dump(swigCPtr, this);
  }

  public boolean acceptHttpMethod(Provider remote_provider, int protocol_type, int http_method, boolean initiate_profile) {
    return lassoJNI.Provider_acceptHttpMethod(swigCPtr, this, Provider.getCPtr(remote_provider), remote_provider, protocol_type, http_method, initiate_profile);
  }

  public String getAssertionConsumerServiceUrl(String service_id) {
    return lassoJNI.Provider_getAssertionConsumerServiceUrl(swigCPtr, this, service_id);
  }

  public String getBase64SuccinctId() {
    return lassoJNI.Provider_getBase64SuccinctId(swigCPtr, this);
  }

  public String getOrganization() {
    return lassoJNI.Provider_getOrganization(swigCPtr, this);
  }

  public int getFirstHttpMethod(Provider remote_provider, int protocol_type) {
    return lassoJNI.Provider_getFirstHttpMethod(swigCPtr, this, Provider.getCPtr(remote_provider), remote_provider, protocol_type);
  }

  public String getMetadataOne(String name) {
    return lassoJNI.Provider_getMetadataOne(swigCPtr, this, name);
  }

  public boolean hasProtocolProfile(int protocol_type, String protocol_profile) {
    return lassoJNI.Provider_hasProtocolProfile(swigCPtr, this, protocol_type, protocol_profile);
  }

  public int getProtocolConformance() {
    return lassoJNI.Provider_getProtocolConformance(swigCPtr, this);
  }

  public void setEncryptionMode(int encryption_mode) {
    lassoJNI.Provider_setEncryptionMode(swigCPtr, this, encryption_mode);
  }

  public void setEncryptionSymKeyType(int encryption_sym_key_type) {
    lassoJNI.Provider_setEncryptionSymKeyType(swigCPtr, this, encryption_sym_key_type);
  }

}
