/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Samlp2StatusDetail extends Node {
  protected Samlp2StatusDetail(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Samlp2StatusDetail obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public Samlp2StatusDetail() {
    this(lassoJNI.new_Samlp2StatusDetail(), true);
  }

  public String dump() {
    return lassoJNI.Samlp2StatusDetail_dump(swigCPtr);
  }

}
