/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlSubjectStatementAbstract extends SamlStatementAbstract {
  protected SamlSubjectStatementAbstract(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlSubjectStatementAbstract obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void delete() {
  super.delete();
}

  public void setSubject(SamlSubject value) {
    lassoJNI.SamlSubjectStatementAbstract_subject_set(swigCPtr, this, SamlSubject.getCPtr(value), value);
  }

  public SamlSubject getSubject() {
    long cPtr = lassoJNI.SamlSubjectStatementAbstract_subject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SamlSubject(cPtr, false);
  }

  public String dump() {
    return lassoJNI.SamlSubjectStatementAbstract_dump(swigCPtr, this);
  }

}
