/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Samlp2NameIDPolicy extends Node {
  protected Samlp2NameIDPolicy(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Samlp2NameIDPolicy obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setFormat(String value) {
    lassoJNI.Samlp2NameIDPolicy_format_set(swigCPtr, this, value);
  }

  public String getFormat() {
    return lassoJNI.Samlp2NameIDPolicy_format_get(swigCPtr, this);
  }

  public void setSpNameQualifier(String value) {
    lassoJNI.Samlp2NameIDPolicy_spNameQualifier_set(swigCPtr, this, value);
  }

  public String getSpNameQualifier() {
    return lassoJNI.Samlp2NameIDPolicy_spNameQualifier_get(swigCPtr, this);
  }

  public void setAllowCreate(boolean value) {
    lassoJNI.Samlp2NameIDPolicy_allowCreate_set(swigCPtr, this, value);
  }

  public boolean getAllowCreate() {
    return lassoJNI.Samlp2NameIDPolicy_allowCreate_get(swigCPtr, this);
  }

  public Samlp2NameIDPolicy() {
    this(lassoJNI.new_Samlp2NameIDPolicy(), true);
  }

  public String dump() {
    return lassoJNI.Samlp2NameIDPolicy_dump(swigCPtr, this);
  }

}
