/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Samlp2IDPEntry extends Node {
  protected Samlp2IDPEntry(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Samlp2IDPEntry obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setProviderId(String value) {
    lassoJNI.Samlp2IDPEntry_providerId_set(swigCPtr, value);
  }

  public String getProviderId() {
    return lassoJNI.Samlp2IDPEntry_providerId_get(swigCPtr);
  }

  public void setName(String value) {
    lassoJNI.Samlp2IDPEntry_Name_set(swigCPtr, value);
  }

  public String getName() {
    return lassoJNI.Samlp2IDPEntry_Name_get(swigCPtr);
  }

  public void setLoc(String value) {
    lassoJNI.Samlp2IDPEntry_Loc_set(swigCPtr, value);
  }

  public String getLoc() {
    return lassoJNI.Samlp2IDPEntry_Loc_get(swigCPtr);
  }

  public Samlp2IDPEntry() {
    this(lassoJNI.new_Samlp2IDPEntry(), true);
  }

  public String dump() {
    return lassoJNI.Samlp2IDPEntry_dump(swigCPtr);
  }

}
