/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlConditions extends Node {
  protected SamlConditions(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlConditions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setNotBefore(String NotBefore) {
    lassoJNI.set_SamlConditions_notBefore(swigCPtr, NotBefore);
  }

  public String getNotBefore() {
    return lassoJNI.get_SamlConditions_notBefore(swigCPtr);
  }

  public void setNotOnOrAfter(String NotOnOrAfter) {
    lassoJNI.set_SamlConditions_notOnOrAfter(swigCPtr, NotOnOrAfter);
  }

  public String getNotOnOrAfter() {
    return lassoJNI.get_SamlConditions_notOnOrAfter(swigCPtr);
  }

  public void setAudienceRestrictionCondition(NodeList AudienceRestrictionCondition) {
    lassoJNI.set_SamlConditions_audienceRestrictionCondition(swigCPtr, NodeList.getCPtr(AudienceRestrictionCondition));
  }

  public NodeList getAudienceRestrictionCondition() {
    long cPtr = lassoJNI.get_SamlConditions_audienceRestrictionCondition(swigCPtr);
    return (cPtr == 0) ? null : new NodeList(cPtr, false);
  }

  public void setCondition(NodeList Condition) {
    lassoJNI.set_SamlConditions_condition(swigCPtr, NodeList.getCPtr(Condition));
  }

  public NodeList getCondition() {
    long cPtr = lassoJNI.get_SamlConditions_condition(swigCPtr);
    return (cPtr == 0) ? null : new NodeList(cPtr, false);
  }

  public SamlConditions() {
    this(lassoJNI.new_SamlConditions(), true);
  }

  public String dump() {
    return lassoJNI.SamlConditions_dump(swigCPtr);
  }

}
