/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlStatementAbstract extends Node {
  protected SamlStatementAbstract(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlStatementAbstract obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void delete() {
  super.delete();
}

  public String dump() {
    return lassoJNI.SamlStatementAbstract_dump(swigCPtr, this);
  }

}
