/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Samlp2ArtifactResolve extends Samlp2RequestAbstract {
  protected Samlp2ArtifactResolve(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Samlp2ArtifactResolve obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setArtifact(String value) {
    lassoJNI.Samlp2ArtifactResolve_Artifact_set(swigCPtr, value);
  }

  public String getArtifact() {
    return lassoJNI.Samlp2ArtifactResolve_Artifact_get(swigCPtr);
  }

  public void setIssuer(Saml2NameID value) {
    lassoJNI.Samlp2ArtifactResolve_issuer_set(swigCPtr, Saml2NameID.getCPtr(value));
  }

  public Saml2NameID getIssuer() {
    long cPtr = lassoJNI.Samlp2ArtifactResolve_issuer_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setExtensions(Samlp2Extensions value) {
    lassoJNI.Samlp2ArtifactResolve_Extensions_set(swigCPtr, Samlp2Extensions.getCPtr(value));
  }

  public Samlp2Extensions getExtensions() {
    long cPtr = lassoJNI.Samlp2ArtifactResolve_Extensions_get(swigCPtr);
    return (cPtr == 0) ? null : new Samlp2Extensions(cPtr, false);
  }

  public void setID(String value) {
    lassoJNI.Samlp2ArtifactResolve_ID_set(swigCPtr, value);
  }

  public String getID() {
    return lassoJNI.Samlp2ArtifactResolve_ID_get(swigCPtr);
  }

  public void setVersion(String value) {
    lassoJNI.Samlp2ArtifactResolve_Version_set(swigCPtr, value);
  }

  public String getVersion() {
    return lassoJNI.Samlp2ArtifactResolve_Version_get(swigCPtr);
  }

  public void setIssueInstant(String value) {
    lassoJNI.Samlp2ArtifactResolve_issueInstant_set(swigCPtr, value);
  }

  public String getIssueInstant() {
    return lassoJNI.Samlp2ArtifactResolve_issueInstant_get(swigCPtr);
  }

  public void setDestination(String value) {
    lassoJNI.Samlp2ArtifactResolve_Destination_set(swigCPtr, value);
  }

  public String getDestination() {
    return lassoJNI.Samlp2ArtifactResolve_Destination_get(swigCPtr);
  }

  public void setConsent(String value) {
    lassoJNI.Samlp2ArtifactResolve_Consent_set(swigCPtr, value);
  }

  public String getConsent() {
    return lassoJNI.Samlp2ArtifactResolve_Consent_get(swigCPtr);
  }

  public Samlp2ArtifactResolve() {
    this(lassoJNI.new_Samlp2ArtifactResolve(), true);
  }

  public String dump() {
    return lassoJNI.Samlp2ArtifactResolve_dump(swigCPtr);
  }

}
