/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2SubjectConfirmation extends Node {
  protected Saml2SubjectConfirmation(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2SubjectConfirmation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setMethod(String value) {
    lassoJNI.Saml2SubjectConfirmation_method_set(swigCPtr, this, value);
  }

  public String getMethod() {
    return lassoJNI.Saml2SubjectConfirmation_method_get(swigCPtr, this);
  }

  public void setBaseID(Saml2BaseIDAbstract value) {
    lassoJNI.Saml2SubjectConfirmation_baseID_set(swigCPtr, this, Saml2BaseIDAbstract.getCPtr(value), value);
  }

  public Saml2BaseIDAbstract getBaseID() {
    long cPtr = lassoJNI.Saml2SubjectConfirmation_baseID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2BaseIDAbstract(cPtr, false);
  }

  public void setNameID(Saml2NameID value) {
    lassoJNI.Saml2SubjectConfirmation_nameID_set(swigCPtr, this, Saml2NameID.getCPtr(value), value);
  }

  public Saml2NameID getNameID() {
    long cPtr = lassoJNI.Saml2SubjectConfirmation_nameID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setEncryptedID(Saml2EncryptedElement value) {
    lassoJNI.Saml2SubjectConfirmation_encryptedID_set(swigCPtr, this, Saml2EncryptedElement.getCPtr(value), value);
  }

  public Saml2EncryptedElement getEncryptedID() {
    long cPtr = lassoJNI.Saml2SubjectConfirmation_encryptedID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2EncryptedElement(cPtr, false);
  }

  public void setSubjectConfirmationData(Saml2SubjectConfirmationData value) {
    lassoJNI.Saml2SubjectConfirmation_subjectConfirmationData_set(swigCPtr, this, Saml2SubjectConfirmationData.getCPtr(value), value);
  }

  public Saml2SubjectConfirmationData getSubjectConfirmationData() {
    long cPtr = lassoJNI.Saml2SubjectConfirmation_subjectConfirmationData_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2SubjectConfirmationData(cPtr, false);
  }

  public Saml2SubjectConfirmation() {
    this(lassoJNI.new_Saml2SubjectConfirmation(), true);
  }

  public String dump() {
    return lassoJNI.Saml2SubjectConfirmation_dump(swigCPtr, this);
  }

}
