/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlAttributeStatement extends SamlSubjectStatementAbstract {
  protected SamlAttributeStatement(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlAttributeStatement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setSubject(SamlSubject value) {
    lassoJNI.SamlAttributeStatement_subject_set(swigCPtr, this, SamlSubject.getCPtr(value), value);
  }

  public SamlSubject getSubject() {
    long cPtr = lassoJNI.SamlAttributeStatement_subject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SamlSubject(cPtr, false);
  }

  public void setAttribute(NodeList value) {
    lassoJNI.SamlAttributeStatement_attribute_set(swigCPtr, this, NodeList.getCPtr(value), value);
  }

  public NodeList getAttribute() {
    long cPtr = lassoJNI.SamlAttributeStatement_attribute_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NodeList(cPtr, false);
  }

  public SamlAttributeStatement() {
    this(lassoJNI.new_SamlAttributeStatement(), true);
  }

  public String dump() {
    return lassoJNI.SamlAttributeStatement_dump(swigCPtr, this);
  }

}
