/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlpRequest extends SamlpRequestAbstract {
  protected SamlpRequest(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlpRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAssertionArtifact(String AssertionArtifact) {
    lassoJNI.set_SamlpRequest_assertionArtifact(swigCPtr, AssertionArtifact);
  }

  public String getAssertionArtifact() {
    return lassoJNI.get_SamlpRequest_assertionArtifact(swigCPtr);
  }

  public void setCertificateFile(String certificate_file) {
    lassoJNI.set_SamlpRequest_certificateFile(swigCPtr, certificate_file);
  }

  public String getCertificateFile() {
    return lassoJNI.get_SamlpRequest_certificateFile(swigCPtr);
  }

  public void setIssueInstant(String IssueInstant) {
    lassoJNI.set_SamlpRequest_issueInstant(swigCPtr, IssueInstant);
  }

  public String getIssueInstant() {
    return lassoJNI.get_SamlpRequest_issueInstant(swigCPtr);
  }

  public void setMajorVersion(int MajorVersion) {
    lassoJNI.set_SamlpRequest_majorVersion(swigCPtr, MajorVersion);
  }

  public int getMajorVersion() {
    return lassoJNI.get_SamlpRequest_majorVersion(swigCPtr);
  }

  public void setMinorVersion(int MinorVersion) {
    lassoJNI.set_SamlpRequest_minorVersion(swigCPtr, MinorVersion);
  }

  public int getMinorVersion() {
    return lassoJNI.get_SamlpRequest_minorVersion(swigCPtr);
  }

  public void setPrivateKeyFile(String private_key_file) {
    lassoJNI.set_SamlpRequest_privateKeyFile(swigCPtr, private_key_file);
  }

  public String getPrivateKeyFile() {
    return lassoJNI.get_SamlpRequest_privateKeyFile(swigCPtr);
  }

  public void setRequestId(String RequestID) {
    lassoJNI.set_SamlpRequest_requestId(swigCPtr, RequestID);
  }

  public String getRequestId() {
    return lassoJNI.get_SamlpRequest_requestId(swigCPtr);
  }

  public void setRespondWith(StringList RespondWith) {
    lassoJNI.set_SamlpRequest_respondWith(swigCPtr, StringList.getCPtr(RespondWith));
  }

  public StringList getRespondWith() {
    long cPtr = lassoJNI.get_SamlpRequest_respondWith(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public void setSignMethod(int sign_method) {
    lassoJNI.set_SamlpRequest_signMethod(swigCPtr, sign_method);
  }

  public int getSignMethod() {
    return lassoJNI.get_SamlpRequest_signMethod(swigCPtr);
  }

  public void setSignType(SWIGTYPE_p_LassoSignatureType sign_type) {
    lassoJNI.set_SamlpRequest_signType(swigCPtr, SWIGTYPE_p_LassoSignatureType.getCPtr(sign_type));
  }

  public SWIGTYPE_p_LassoSignatureType getSignType() {
    return new SWIGTYPE_p_LassoSignatureType(lassoJNI.get_SamlpRequest_signType(swigCPtr), true);
  }

  public SamlpRequest() {
    this(lassoJNI.new_SamlpRequest(), true);
  }

  public String dump() {
    return lassoJNI.SamlpRequest_dump(swigCPtr);
  }

}
