/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlpStatus extends Node {
  protected SamlpStatus(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlpStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setStatusMessage(String value) {
    lassoJNI.SamlpStatus_statusMessage_set(swigCPtr, this, value);
  }

  public String getStatusMessage() {
    return lassoJNI.SamlpStatus_statusMessage_get(swigCPtr, this);
  }

  public void setStatusCode(SamlpStatusCode value) {
    lassoJNI.SamlpStatus_statusCode_set(swigCPtr, this, SamlpStatusCode.getCPtr(value), value);
  }

  public SamlpStatusCode getStatusCode() {
    long cPtr = lassoJNI.SamlpStatus_statusCode_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SamlpStatusCode(cPtr, false);
  }

  public SamlpStatus() {
    this(lassoJNI.new_SamlpStatus(), true);
  }

  public String dump() {
    return lassoJNI.SamlpStatus_dump(swigCPtr, this);
  }

}
