/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2AuthnStatement extends Saml2StatementAbstract {
  protected Saml2AuthnStatement(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2AuthnStatement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAuthnInstant(String value) {
    lassoJNI.Saml2AuthnStatement_authnInstant_set(swigCPtr, this, value);
  }

  public String getAuthnInstant() {
    return lassoJNI.Saml2AuthnStatement_authnInstant_get(swigCPtr, this);
  }

  public void setSessionIndex(String value) {
    lassoJNI.Saml2AuthnStatement_sessionIndex_set(swigCPtr, this, value);
  }

  public String getSessionIndex() {
    return lassoJNI.Saml2AuthnStatement_sessionIndex_get(swigCPtr, this);
  }

  public void setSessionNotOnOrAfter(String value) {
    lassoJNI.Saml2AuthnStatement_sessionNotOnOrAfter_set(swigCPtr, this, value);
  }

  public String getSessionNotOnOrAfter() {
    return lassoJNI.Saml2AuthnStatement_sessionNotOnOrAfter_get(swigCPtr, this);
  }

  public void setSubjectLocality(Saml2SubjectLocality value) {
    lassoJNI.Saml2AuthnStatement_subjectLocality_set(swigCPtr, this, Saml2SubjectLocality.getCPtr(value), value);
  }

  public Saml2SubjectLocality getSubjectLocality() {
    long cPtr = lassoJNI.Saml2AuthnStatement_subjectLocality_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2SubjectLocality(cPtr, false);
  }

  public void setAuthnContext(Saml2AuthnContext value) {
    lassoJNI.Saml2AuthnStatement_authnContext_set(swigCPtr, this, Saml2AuthnContext.getCPtr(value), value);
  }

  public Saml2AuthnContext getAuthnContext() {
    long cPtr = lassoJNI.Saml2AuthnStatement_authnContext_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2AuthnContext(cPtr, false);
  }

  public Saml2AuthnStatement() {
    this(lassoJNI.new_Saml2AuthnStatement(), true);
  }

  public String dump() {
    return lassoJNI.Saml2AuthnStatement_dump(swigCPtr, this);
  }

}
