/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlAuthorityBinding extends Node {
  protected SamlAuthorityBinding(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlAuthorityBinding obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAuthorityKind(String value) {
    lassoJNI.SamlAuthorityBinding_authorityKind_set(swigCPtr, this, value);
  }

  public String getAuthorityKind() {
    return lassoJNI.SamlAuthorityBinding_authorityKind_get(swigCPtr, this);
  }

  public void setLocation(String value) {
    lassoJNI.SamlAuthorityBinding_location_set(swigCPtr, this, value);
  }

  public String getLocation() {
    return lassoJNI.SamlAuthorityBinding_location_get(swigCPtr, this);
  }

  public void setBinding(String value) {
    lassoJNI.SamlAuthorityBinding_binding_set(swigCPtr, this, value);
  }

  public String getBinding() {
    return lassoJNI.SamlAuthorityBinding_binding_get(swigCPtr, this);
  }

  public SamlAuthorityBinding() {
    this(lassoJNI.new_SamlAuthorityBinding(), true);
  }

  public String dump() {
    return lassoJNI.SamlAuthorityBinding_dump(swigCPtr, this);
  }

}
