/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2AuthzDecisionStatement extends Saml2StatementAbstract {
  protected Saml2AuthzDecisionStatement(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2AuthzDecisionStatement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setResource(String value) {
    lassoJNI.Saml2AuthzDecisionStatement_Resource_set(swigCPtr, value);
  }

  public String getResource() {
    return lassoJNI.Saml2AuthzDecisionStatement_Resource_get(swigCPtr);
  }

  public void setDecision(String value) {
    lassoJNI.Saml2AuthzDecisionStatement_Decision_set(swigCPtr, value);
  }

  public String getDecision() {
    return lassoJNI.Saml2AuthzDecisionStatement_Decision_get(swigCPtr);
  }

  public void setAction(Saml2Action value) {
    lassoJNI.Saml2AuthzDecisionStatement_action_set(swigCPtr, Saml2Action.getCPtr(value));
  }

  public Saml2Action getAction() {
    long cPtr = lassoJNI.Saml2AuthzDecisionStatement_action_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2Action(cPtr, false);
  }

  public void setEvidence(Saml2Evidence value) {
    lassoJNI.Saml2AuthzDecisionStatement_evidence_set(swigCPtr, Saml2Evidence.getCPtr(value));
  }

  public Saml2Evidence getEvidence() {
    long cPtr = lassoJNI.Saml2AuthzDecisionStatement_evidence_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2Evidence(cPtr, false);
  }

  public Saml2AuthzDecisionStatement() {
    this(lassoJNI.new_Saml2AuthzDecisionStatement(), true);
  }

  public String dump() {
    return lassoJNI.Saml2AuthzDecisionStatement_dump(swigCPtr);
  }

}
