/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlAuthenticationStatement extends SamlSubjectStatementAbstract {
  protected SamlAuthenticationStatement(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlAuthenticationStatement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAuthenticationInstant(String AuthenticationInstant) {
    lassoJNI.set_SamlAuthenticationStatement_authenticationInstant(swigCPtr, AuthenticationInstant);
  }

  public String getAuthenticationInstant() {
    return lassoJNI.get_SamlAuthenticationStatement_authenticationInstant(swigCPtr);
  }

  public void setAuthenticationMethod(String AuthenticationMethod) {
    lassoJNI.set_SamlAuthenticationStatement_authenticationMethod(swigCPtr, AuthenticationMethod);
  }

  public String getAuthenticationMethod() {
    return lassoJNI.get_SamlAuthenticationStatement_authenticationMethod(swigCPtr);
  }

  public void setAuthorityBinding(NodeList AuthorityBinding) {
    lassoJNI.set_SamlAuthenticationStatement_authorityBinding(swigCPtr, NodeList.getCPtr(AuthorityBinding));
  }

  public NodeList getAuthorityBinding() {
    long cPtr = lassoJNI.get_SamlAuthenticationStatement_authorityBinding(swigCPtr);
    return (cPtr == 0) ? null : new NodeList(cPtr, false);
  }

  public void setSubjectLocality(SamlSubjectLocality SubjectLocality) {
    lassoJNI.set_SamlAuthenticationStatement_subjectLocality(swigCPtr, SamlSubjectLocality.getCPtr(SubjectLocality));
  }

  public SamlSubjectLocality getSubjectLocality() {
    long cPtr = lassoJNI.get_SamlAuthenticationStatement_subjectLocality(swigCPtr);
    return (cPtr == 0) ? null : new SamlSubjectLocality(cPtr, false);
  }

  public SamlAuthenticationStatement() {
    this(lassoJNI.new_SamlAuthenticationStatement(), true);
  }

  public String dump() {
    return lassoJNI.SamlAuthenticationStatement_dump(swigCPtr);
  }

}
