/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlpStatusCode extends Node {
  protected SamlpStatusCode(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlpStatusCode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setValue(String value) {
    lassoJNI.SamlpStatusCode_value_set(swigCPtr, this, value);
  }

  public String getValue() {
    return lassoJNI.SamlpStatusCode_value_get(swigCPtr, this);
  }

  public void setStatusCode(SamlpStatusCode value) {
    lassoJNI.SamlpStatusCode_statusCode_set(swigCPtr, this, SamlpStatusCode.getCPtr(value), value);
  }

  public SamlpStatusCode getStatusCode() {
    long cPtr = lassoJNI.SamlpStatusCode_statusCode_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SamlpStatusCode(cPtr, false);
  }

  public SamlpStatusCode() {
    this(lassoJNI.new_SamlpStatusCode(), true);
  }

  public String dump() {
    return lassoJNI.SamlpStatusCode_dump(swigCPtr, this);
  }

}
