/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlAuthorityBinding extends Node {
  protected SamlAuthorityBinding(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlAuthorityBinding obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAuthorityKind(String AuthorityKind) {
    lassoJNI.set_SamlAuthorityBinding_authorityKind(swigCPtr, AuthorityKind);
  }

  public String getAuthorityKind() {
    return lassoJNI.get_SamlAuthorityBinding_authorityKind(swigCPtr);
  }

  public void setLocation(String Location) {
    lassoJNI.set_SamlAuthorityBinding_location(swigCPtr, Location);
  }

  public String getLocation() {
    return lassoJNI.get_SamlAuthorityBinding_location(swigCPtr);
  }

  public void setBinding(String Binding) {
    lassoJNI.set_SamlAuthorityBinding_binding(swigCPtr, Binding);
  }

  public String getBinding() {
    return lassoJNI.get_SamlAuthorityBinding_binding(swigCPtr);
  }

  public SamlAuthorityBinding() {
    this(lassoJNI.new_SamlAuthorityBinding(), true);
  }

  public String dump() {
    return lassoJNI.SamlAuthorityBinding_dump(swigCPtr);
  }

}
