/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlAdvice extends Node {
  protected SamlAdvice(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlAdvice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAssertion(SamlAssertion value) {
    lassoJNI.SamlAdvice_assertion_set(swigCPtr, this, SamlAssertion.getCPtr(value), value);
  }

  public SamlAssertion getAssertion() {
    long cPtr = lassoJNI.SamlAdvice_assertion_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SamlAssertion(cPtr, false);
  }

  public void setAssertionIdReference(StringList value) {
    lassoJNI.SamlAdvice_assertionIdReference_set(swigCPtr, this, StringList.getCPtr(value), value);
  }

  public StringList getAssertionIdReference() {
    long cPtr = lassoJNI.SamlAdvice_assertionIdReference_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public SamlAdvice() {
    this(lassoJNI.new_SamlAdvice(), true);
  }

  public String dump() {
    return lassoJNI.SamlAdvice_dump(swigCPtr, this);
  }

}
