/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Samlp2AuthzDecisionQuery extends Samlp2SubjectQueryAbstract {
  protected Samlp2AuthzDecisionQuery(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Samlp2AuthzDecisionQuery obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setResource(String value) {
    lassoJNI.Samlp2AuthzDecisionQuery_Resource_set(swigCPtr, value);
  }

  public String getResource() {
    return lassoJNI.Samlp2AuthzDecisionQuery_Resource_get(swigCPtr);
  }

  public void setAction(Saml2Action value) {
    lassoJNI.Samlp2AuthzDecisionQuery_action_set(swigCPtr, Saml2Action.getCPtr(value));
  }

  public Saml2Action getAction() {
    long cPtr = lassoJNI.Samlp2AuthzDecisionQuery_action_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2Action(cPtr, false);
  }

  public void setEvidence(Saml2Evidence value) {
    lassoJNI.Samlp2AuthzDecisionQuery_evidence_set(swigCPtr, Saml2Evidence.getCPtr(value));
  }

  public Saml2Evidence getEvidence() {
    long cPtr = lassoJNI.Samlp2AuthzDecisionQuery_evidence_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2Evidence(cPtr, false);
  }

  public void setSubject(Saml2Subject value) {
    lassoJNI.Samlp2AuthzDecisionQuery_Subject_set(swigCPtr, Saml2Subject.getCPtr(value));
  }

  public Saml2Subject getSubject() {
    long cPtr = lassoJNI.Samlp2AuthzDecisionQuery_Subject_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2Subject(cPtr, false);
  }

  public void setIssuer(Saml2NameID value) {
    lassoJNI.Samlp2AuthzDecisionQuery_issuer_set(swigCPtr, Saml2NameID.getCPtr(value));
  }

  public Saml2NameID getIssuer() {
    long cPtr = lassoJNI.Samlp2AuthzDecisionQuery_issuer_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setExtensions(Samlp2Extensions value) {
    lassoJNI.Samlp2AuthzDecisionQuery_Extensions_set(swigCPtr, Samlp2Extensions.getCPtr(value));
  }

  public Samlp2Extensions getExtensions() {
    long cPtr = lassoJNI.Samlp2AuthzDecisionQuery_Extensions_get(swigCPtr);
    return (cPtr == 0) ? null : new Samlp2Extensions(cPtr, false);
  }

  public void setID(String value) {
    lassoJNI.Samlp2AuthzDecisionQuery_ID_set(swigCPtr, value);
  }

  public String getID() {
    return lassoJNI.Samlp2AuthzDecisionQuery_ID_get(swigCPtr);
  }

  public void setVersion(String value) {
    lassoJNI.Samlp2AuthzDecisionQuery_Version_set(swigCPtr, value);
  }

  public String getVersion() {
    return lassoJNI.Samlp2AuthzDecisionQuery_Version_get(swigCPtr);
  }

  public void setIssueInstant(String value) {
    lassoJNI.Samlp2AuthzDecisionQuery_issueInstant_set(swigCPtr, value);
  }

  public String getIssueInstant() {
    return lassoJNI.Samlp2AuthzDecisionQuery_issueInstant_get(swigCPtr);
  }

  public void setDestination(String value) {
    lassoJNI.Samlp2AuthzDecisionQuery_Destination_set(swigCPtr, value);
  }

  public String getDestination() {
    return lassoJNI.Samlp2AuthzDecisionQuery_Destination_get(swigCPtr);
  }

  public void setConsent(String value) {
    lassoJNI.Samlp2AuthzDecisionQuery_Consent_set(swigCPtr, value);
  }

  public String getConsent() {
    return lassoJNI.Samlp2AuthzDecisionQuery_Consent_get(swigCPtr);
  }

  public Samlp2AuthzDecisionQuery() {
    this(lassoJNI.new_Samlp2AuthzDecisionQuery(), true);
  }

  public String dump() {
    return lassoJNI.Samlp2AuthzDecisionQuery_dump(swigCPtr);
  }

}
