/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Samlp2NameIDMappingRequest extends Samlp2RequestAbstract {
  protected Samlp2NameIDMappingRequest(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Samlp2NameIDMappingRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setBaseID(Saml2BaseIDAbstract value) {
    lassoJNI.Samlp2NameIDMappingRequest_baseID_set(swigCPtr, this, Saml2BaseIDAbstract.getCPtr(value), value);
  }

  public Saml2BaseIDAbstract getBaseID() {
    long cPtr = lassoJNI.Samlp2NameIDMappingRequest_baseID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2BaseIDAbstract(cPtr, false);
  }

  public void setNameID(Saml2NameID value) {
    lassoJNI.Samlp2NameIDMappingRequest_nameID_set(swigCPtr, this, Saml2NameID.getCPtr(value), value);
  }

  public Saml2NameID getNameID() {
    long cPtr = lassoJNI.Samlp2NameIDMappingRequest_nameID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setEncryptedID(Saml2EncryptedElement value) {
    lassoJNI.Samlp2NameIDMappingRequest_encryptedID_set(swigCPtr, this, Saml2EncryptedElement.getCPtr(value), value);
  }

  public Saml2EncryptedElement getEncryptedID() {
    long cPtr = lassoJNI.Samlp2NameIDMappingRequest_encryptedID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2EncryptedElement(cPtr, false);
  }

  public void setNameIDPolicy(Samlp2NameIDPolicy value) {
    lassoJNI.Samlp2NameIDMappingRequest_nameIDPolicy_set(swigCPtr, this, Samlp2NameIDPolicy.getCPtr(value), value);
  }

  public Samlp2NameIDPolicy getNameIDPolicy() {
    long cPtr = lassoJNI.Samlp2NameIDMappingRequest_nameIDPolicy_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Samlp2NameIDPolicy(cPtr, false);
  }

  public void setIssuer(Saml2NameID value) {
    lassoJNI.Samlp2NameIDMappingRequest_issuer_set(swigCPtr, this, Saml2NameID.getCPtr(value), value);
  }

  public Saml2NameID getIssuer() {
    long cPtr = lassoJNI.Samlp2NameIDMappingRequest_issuer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setExtensions(Samlp2Extensions value) {
    lassoJNI.Samlp2NameIDMappingRequest_extensions_set(swigCPtr, this, Samlp2Extensions.getCPtr(value), value);
  }

  public Samlp2Extensions getExtensions() {
    long cPtr = lassoJNI.Samlp2NameIDMappingRequest_extensions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Samlp2Extensions(cPtr, false);
  }

  public void setID(String value) {
    lassoJNI.Samlp2NameIDMappingRequest_iD_set(swigCPtr, this, value);
  }

  public String getID() {
    return lassoJNI.Samlp2NameIDMappingRequest_iD_get(swigCPtr, this);
  }

  public void setVersion(String value) {
    lassoJNI.Samlp2NameIDMappingRequest_version_set(swigCPtr, this, value);
  }

  public String getVersion() {
    return lassoJNI.Samlp2NameIDMappingRequest_version_get(swigCPtr, this);
  }

  public void setIssueInstant(String value) {
    lassoJNI.Samlp2NameIDMappingRequest_issueInstant_set(swigCPtr, this, value);
  }

  public String getIssueInstant() {
    return lassoJNI.Samlp2NameIDMappingRequest_issueInstant_get(swigCPtr, this);
  }

  public void setDestination(String value) {
    lassoJNI.Samlp2NameIDMappingRequest_destination_set(swigCPtr, this, value);
  }

  public String getDestination() {
    return lassoJNI.Samlp2NameIDMappingRequest_destination_get(swigCPtr, this);
  }

  public void setConsent(String value) {
    lassoJNI.Samlp2NameIDMappingRequest_consent_set(swigCPtr, this, value);
  }

  public String getConsent() {
    return lassoJNI.Samlp2NameIDMappingRequest_consent_get(swigCPtr, this);
  }

  public Samlp2NameIDMappingRequest() {
    this(lassoJNI.new_Samlp2NameIDMappingRequest(), true);
  }

  public String dump() {
    return lassoJNI.Samlp2NameIDMappingRequest_dump(swigCPtr, this);
  }

}
