/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlpStatus extends Node {
  protected SamlpStatus(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlpStatus obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setStatusMessage(String StatusMessage) {
    lassoJNI.set_SamlpStatus_statusMessage(swigCPtr, StatusMessage);
  }

  public String getStatusMessage() {
    return lassoJNI.get_SamlpStatus_statusMessage(swigCPtr);
  }

  public void setStatusCode(SamlpStatusCode StatusCode) {
    lassoJNI.set_SamlpStatus_statusCode(swigCPtr, SamlpStatusCode.getCPtr(StatusCode));
  }

  public SamlpStatusCode getStatusCode() {
    long cPtr = lassoJNI.get_SamlpStatus_statusCode(swigCPtr);
    return (cPtr == 0) ? null : new SamlpStatusCode(cPtr, false);
  }

  public SamlpStatus() {
    this(lassoJNI.new_SamlpStatus(), true);
  }

  public String dump() {
    return lassoJNI.SamlpStatus_dump(swigCPtr);
  }

}
