/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Samlp2IDPList extends Node {
  protected Samlp2IDPList(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Samlp2IDPList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setGetComplete(String value) {
    lassoJNI.Samlp2IDPList_GetComplete_set(swigCPtr, value);
  }

  public String getGetComplete() {
    return lassoJNI.Samlp2IDPList_GetComplete_get(swigCPtr);
  }

  public void setIDPEntry(Samlp2IDPEntry value) {
    lassoJNI.Samlp2IDPList_iDPEntry_set(swigCPtr, Samlp2IDPEntry.getCPtr(value));
  }

  public Samlp2IDPEntry getIDPEntry() {
    long cPtr = lassoJNI.Samlp2IDPList_iDPEntry_get(swigCPtr);
    return (cPtr == 0) ? null : new Samlp2IDPEntry(cPtr, false);
  }

  public Samlp2IDPList() {
    this(lassoJNI.new_Samlp2IDPList(), true);
  }

  public String dump() {
    return lassoJNI.Samlp2IDPList_dump(swigCPtr);
  }

}
