/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlpRequestAbstract extends Node {
  protected SamlpRequestAbstract(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlpRequestAbstract obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void delete() {
  super.delete();
}

  public void setCertificateFile(String value) {
    lassoJNI.SamlpRequestAbstract_certificateFile_set(swigCPtr, this, value);
  }

  public String getCertificateFile() {
    return lassoJNI.SamlpRequestAbstract_certificateFile_get(swigCPtr, this);
  }

  public void setIssueInstant(String value) {
    lassoJNI.SamlpRequestAbstract_issueInstant_set(swigCPtr, this, value);
  }

  public String getIssueInstant() {
    return lassoJNI.SamlpRequestAbstract_issueInstant_get(swigCPtr, this);
  }

  public void setMajorVersion(int value) {
    lassoJNI.SamlpRequestAbstract_majorVersion_set(swigCPtr, this, value);
  }

  public int getMajorVersion() {
    return lassoJNI.SamlpRequestAbstract_majorVersion_get(swigCPtr, this);
  }

  public void setMinorVersion(int value) {
    lassoJNI.SamlpRequestAbstract_minorVersion_set(swigCPtr, this, value);
  }

  public int getMinorVersion() {
    return lassoJNI.SamlpRequestAbstract_minorVersion_get(swigCPtr, this);
  }

  public void setPrivateKeyFile(String value) {
    lassoJNI.SamlpRequestAbstract_privateKeyFile_set(swigCPtr, this, value);
  }

  public String getPrivateKeyFile() {
    return lassoJNI.SamlpRequestAbstract_privateKeyFile_get(swigCPtr, this);
  }

  public void setRequestId(String value) {
    lassoJNI.SamlpRequestAbstract_requestId_set(swigCPtr, this, value);
  }

  public String getRequestId() {
    return lassoJNI.SamlpRequestAbstract_requestId_get(swigCPtr, this);
  }

  public void setSignMethod(int value) {
    lassoJNI.SamlpRequestAbstract_signMethod_set(swigCPtr, this, value);
  }

  public int getSignMethod() {
    return lassoJNI.SamlpRequestAbstract_signMethod_get(swigCPtr, this);
  }

  public void setSignType(SWIGTYPE_p_LassoSignatureType value) {
    lassoJNI.SamlpRequestAbstract_signType_set(swigCPtr, this, SWIGTYPE_p_LassoSignatureType.getCPtr(value));
  }

  public SWIGTYPE_p_LassoSignatureType getSignType() {
    return new SWIGTYPE_p_LassoSignatureType(lassoJNI.SamlpRequestAbstract_signType_get(swigCPtr, this), true);
  }

  public void setRespondWith(StringList value) {
    lassoJNI.SamlpRequestAbstract_respondWith_set(swigCPtr, this, StringList.getCPtr(value), value);
  }

  public StringList getRespondWith() {
    long cPtr = lassoJNI.SamlpRequestAbstract_respondWith_get(swigCPtr, this);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public String dump() {
    return lassoJNI.SamlpRequestAbstract_dump(swigCPtr, this);
  }

}
