/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Samlp2SubjectQueryAbstract extends Samlp2RequestAbstract {
  protected Samlp2SubjectQueryAbstract(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Samlp2SubjectQueryAbstract obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setSubject(Saml2Subject value) {
    lassoJNI.Samlp2SubjectQueryAbstract_subject_set(swigCPtr, this, Saml2Subject.getCPtr(value), value);
  }

  public Saml2Subject getSubject() {
    long cPtr = lassoJNI.Samlp2SubjectQueryAbstract_subject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2Subject(cPtr, false);
  }

  public void setIssuer(Saml2NameID value) {
    lassoJNI.Samlp2SubjectQueryAbstract_issuer_set(swigCPtr, this, Saml2NameID.getCPtr(value), value);
  }

  public Saml2NameID getIssuer() {
    long cPtr = lassoJNI.Samlp2SubjectQueryAbstract_issuer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setExtensions(Samlp2Extensions value) {
    lassoJNI.Samlp2SubjectQueryAbstract_extensions_set(swigCPtr, this, Samlp2Extensions.getCPtr(value), value);
  }

  public Samlp2Extensions getExtensions() {
    long cPtr = lassoJNI.Samlp2SubjectQueryAbstract_extensions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Samlp2Extensions(cPtr, false);
  }

  public void setID(String value) {
    lassoJNI.Samlp2SubjectQueryAbstract_iD_set(swigCPtr, this, value);
  }

  public String getID() {
    return lassoJNI.Samlp2SubjectQueryAbstract_iD_get(swigCPtr, this);
  }

  public void setVersion(String value) {
    lassoJNI.Samlp2SubjectQueryAbstract_version_set(swigCPtr, this, value);
  }

  public String getVersion() {
    return lassoJNI.Samlp2SubjectQueryAbstract_version_get(swigCPtr, this);
  }

  public void setIssueInstant(String value) {
    lassoJNI.Samlp2SubjectQueryAbstract_issueInstant_set(swigCPtr, this, value);
  }

  public String getIssueInstant() {
    return lassoJNI.Samlp2SubjectQueryAbstract_issueInstant_get(swigCPtr, this);
  }

  public void setDestination(String value) {
    lassoJNI.Samlp2SubjectQueryAbstract_destination_set(swigCPtr, this, value);
  }

  public String getDestination() {
    return lassoJNI.Samlp2SubjectQueryAbstract_destination_get(swigCPtr, this);
  }

  public void setConsent(String value) {
    lassoJNI.Samlp2SubjectQueryAbstract_consent_set(swigCPtr, this, value);
  }

  public String getConsent() {
    return lassoJNI.Samlp2SubjectQueryAbstract_consent_get(swigCPtr, this);
  }

  public Samlp2SubjectQueryAbstract() {
    this(lassoJNI.new_Samlp2SubjectQueryAbstract(), true);
  }

  public String dump() {
    return lassoJNI.Samlp2SubjectQueryAbstract_dump(swigCPtr, this);
  }

}
