/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlSubjectConfirmation extends Node {
  protected SamlSubjectConfirmation(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlSubjectConfirmation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setSubjectConfirmationData(String value) {
    lassoJNI.SamlSubjectConfirmation_subjectConfirmationData_set(swigCPtr, value);
  }

  public String getSubjectConfirmationData() {
    return lassoJNI.SamlSubjectConfirmation_subjectConfirmationData_get(swigCPtr);
  }

  public void setConfirmationMethod(StringList value) {
    lassoJNI.SamlSubjectConfirmation_confirmationMethod_set(swigCPtr, StringList.getCPtr(value));
  }

  public StringList getConfirmationMethod() {
    long cPtr = lassoJNI.SamlSubjectConfirmation_confirmationMethod_get(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public SamlSubjectConfirmation() {
    this(lassoJNI.new_SamlSubjectConfirmation(), true);
  }

  public String dump() {
    return lassoJNI.SamlSubjectConfirmation_dump(swigCPtr);
  }

}
