/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2Assertion extends Node {
  protected Saml2Assertion(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2Assertion obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setVersion(String value) {
    lassoJNI.Saml2Assertion_version_set(swigCPtr, this, value);
  }

  public String getVersion() {
    return lassoJNI.Saml2Assertion_version_get(swigCPtr, this);
  }

  public void setID(String value) {
    lassoJNI.Saml2Assertion_iD_set(swigCPtr, this, value);
  }

  public String getID() {
    return lassoJNI.Saml2Assertion_iD_get(swigCPtr, this);
  }

  public void setIssueInstant(String value) {
    lassoJNI.Saml2Assertion_issueInstant_set(swigCPtr, this, value);
  }

  public String getIssueInstant() {
    return lassoJNI.Saml2Assertion_issueInstant_get(swigCPtr, this);
  }

  public void setIssuer(Saml2NameID value) {
    lassoJNI.Saml2Assertion_issuer_set(swigCPtr, this, Saml2NameID.getCPtr(value), value);
  }

  public Saml2NameID getIssuer() {
    long cPtr = lassoJNI.Saml2Assertion_issuer_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setSubject(Saml2Subject value) {
    lassoJNI.Saml2Assertion_subject_set(swigCPtr, this, Saml2Subject.getCPtr(value), value);
  }

  public Saml2Subject getSubject() {
    long cPtr = lassoJNI.Saml2Assertion_subject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2Subject(cPtr, false);
  }

  public void setConditions(Saml2Conditions value) {
    lassoJNI.Saml2Assertion_conditions_set(swigCPtr, this, Saml2Conditions.getCPtr(value), value);
  }

  public Saml2Conditions getConditions() {
    long cPtr = lassoJNI.Saml2Assertion_conditions_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2Conditions(cPtr, false);
  }

  public void setAdvice(Saml2Advice value) {
    lassoJNI.Saml2Assertion_advice_set(swigCPtr, this, Saml2Advice.getCPtr(value), value);
  }

  public Saml2Advice getAdvice() {
    long cPtr = lassoJNI.Saml2Assertion_advice_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2Advice(cPtr, false);
  }

  public void setAuthnStatement(NodeList value) {
    lassoJNI.Saml2Assertion_authnStatement_set(swigCPtr, this, NodeList.getCPtr(value), value);
  }

  public NodeList getAuthnStatement() {
    long cPtr = lassoJNI.Saml2Assertion_authnStatement_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NodeList(cPtr, false);
  }

  public Saml2Assertion() {
    this(lassoJNI.new_Saml2Assertion(), true);
  }

  public String dump() {
    return lassoJNI.Saml2Assertion_dump(swigCPtr, this);
  }

}
