/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlpResponseAbstract extends Node {
  protected SamlpResponseAbstract(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlpResponseAbstract obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public void delete() {
  super.delete();
}

  public void setCertificateFile(String value) {
    lassoJNI.SamlpResponseAbstract_certificateFile_set(swigCPtr, this, value);
  }

  public String getCertificateFile() {
    return lassoJNI.SamlpResponseAbstract_certificateFile_get(swigCPtr, this);
  }

  public void setInResponseTo(String value) {
    lassoJNI.SamlpResponseAbstract_inResponseTo_set(swigCPtr, this, value);
  }

  public String getInResponseTo() {
    return lassoJNI.SamlpResponseAbstract_inResponseTo_get(swigCPtr, this);
  }

  public void setIssueInstant(String value) {
    lassoJNI.SamlpResponseAbstract_issueInstant_set(swigCPtr, this, value);
  }

  public String getIssueInstant() {
    return lassoJNI.SamlpResponseAbstract_issueInstant_get(swigCPtr, this);
  }

  public void setMajorVersion(int value) {
    lassoJNI.SamlpResponseAbstract_majorVersion_set(swigCPtr, this, value);
  }

  public int getMajorVersion() {
    return lassoJNI.SamlpResponseAbstract_majorVersion_get(swigCPtr, this);
  }

  public void setMinorVersion(int value) {
    lassoJNI.SamlpResponseAbstract_minorVersion_set(swigCPtr, this, value);
  }

  public int getMinorVersion() {
    return lassoJNI.SamlpResponseAbstract_minorVersion_get(swigCPtr, this);
  }

  public void setPrivateKeyFile(String value) {
    lassoJNI.SamlpResponseAbstract_privateKeyFile_set(swigCPtr, this, value);
  }

  public String getPrivateKeyFile() {
    return lassoJNI.SamlpResponseAbstract_privateKeyFile_get(swigCPtr, this);
  }

  public void setRecipient(String value) {
    lassoJNI.SamlpResponseAbstract_recipient_set(swigCPtr, this, value);
  }

  public String getRecipient() {
    return lassoJNI.SamlpResponseAbstract_recipient_get(swigCPtr, this);
  }

  public void setResponseId(String value) {
    lassoJNI.SamlpResponseAbstract_responseId_set(swigCPtr, this, value);
  }

  public String getResponseId() {
    return lassoJNI.SamlpResponseAbstract_responseId_get(swigCPtr, this);
  }

  public void setSignMethod(int value) {
    lassoJNI.SamlpResponseAbstract_signMethod_set(swigCPtr, this, value);
  }

  public int getSignMethod() {
    return lassoJNI.SamlpResponseAbstract_signMethod_get(swigCPtr, this);
  }

  public void setSignType(SWIGTYPE_p_LassoSignatureType value) {
    lassoJNI.SamlpResponseAbstract_signType_set(swigCPtr, this, SWIGTYPE_p_LassoSignatureType.getCPtr(value));
  }

  public SWIGTYPE_p_LassoSignatureType getSignType() {
    return new SWIGTYPE_p_LassoSignatureType(lassoJNI.SamlpResponseAbstract_signType_get(swigCPtr, this), true);
  }

  public String dump() {
    return lassoJNI.SamlpResponseAbstract_dump(swigCPtr, this);
  }

}
