/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Samlp2ManageNameIDRequest extends Samlp2RequestAbstract {
  protected Samlp2ManageNameIDRequest(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Samlp2ManageNameIDRequest obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setNewID(String value) {
    lassoJNI.Samlp2ManageNameIDRequest_NewID_set(swigCPtr, value);
  }

  public String getNewID() {
    return lassoJNI.Samlp2ManageNameIDRequest_NewID_get(swigCPtr);
  }

  public void setNameID(Saml2NameID value) {
    lassoJNI.Samlp2ManageNameIDRequest_nameID_set(swigCPtr, Saml2NameID.getCPtr(value));
  }

  public Saml2NameID getNameID() {
    long cPtr = lassoJNI.Samlp2ManageNameIDRequest_nameID_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setEncryptedID(Saml2EncryptedElement value) {
    lassoJNI.Samlp2ManageNameIDRequest_encryptedID_set(swigCPtr, Saml2EncryptedElement.getCPtr(value));
  }

  public Saml2EncryptedElement getEncryptedID() {
    long cPtr = lassoJNI.Samlp2ManageNameIDRequest_encryptedID_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2EncryptedElement(cPtr, false);
  }

  public void setNewEncryptedID(Saml2EncryptedElement value) {
    lassoJNI.Samlp2ManageNameIDRequest_newEncryptedID_set(swigCPtr, Saml2EncryptedElement.getCPtr(value));
  }

  public Saml2EncryptedElement getNewEncryptedID() {
    long cPtr = lassoJNI.Samlp2ManageNameIDRequest_newEncryptedID_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2EncryptedElement(cPtr, false);
  }

  public void setTerminate(Samlp2Terminate value) {
    lassoJNI.Samlp2ManageNameIDRequest_terminate_set(swigCPtr, Samlp2Terminate.getCPtr(value));
  }

  public Samlp2Terminate getTerminate() {
    long cPtr = lassoJNI.Samlp2ManageNameIDRequest_terminate_get(swigCPtr);
    return (cPtr == 0) ? null : new Samlp2Terminate(cPtr, false);
  }

  public void setIssuer(Saml2NameID value) {
    lassoJNI.Samlp2ManageNameIDRequest_issuer_set(swigCPtr, Saml2NameID.getCPtr(value));
  }

  public Saml2NameID getIssuer() {
    long cPtr = lassoJNI.Samlp2ManageNameIDRequest_issuer_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setExtensions(Samlp2Extensions value) {
    lassoJNI.Samlp2ManageNameIDRequest_Extensions_set(swigCPtr, Samlp2Extensions.getCPtr(value));
  }

  public Samlp2Extensions getExtensions() {
    long cPtr = lassoJNI.Samlp2ManageNameIDRequest_Extensions_get(swigCPtr);
    return (cPtr == 0) ? null : new Samlp2Extensions(cPtr, false);
  }

  public void setID(String value) {
    lassoJNI.Samlp2ManageNameIDRequest_ID_set(swigCPtr, value);
  }

  public String getID() {
    return lassoJNI.Samlp2ManageNameIDRequest_ID_get(swigCPtr);
  }

  public void setVersion(String value) {
    lassoJNI.Samlp2ManageNameIDRequest_Version_set(swigCPtr, value);
  }

  public String getVersion() {
    return lassoJNI.Samlp2ManageNameIDRequest_Version_get(swigCPtr);
  }

  public void setIssueInstant(String value) {
    lassoJNI.Samlp2ManageNameIDRequest_issueInstant_set(swigCPtr, value);
  }

  public String getIssueInstant() {
    return lassoJNI.Samlp2ManageNameIDRequest_issueInstant_get(swigCPtr);
  }

  public void setDestination(String value) {
    lassoJNI.Samlp2ManageNameIDRequest_Destination_set(swigCPtr, value);
  }

  public String getDestination() {
    return lassoJNI.Samlp2ManageNameIDRequest_Destination_get(swigCPtr);
  }

  public void setConsent(String value) {
    lassoJNI.Samlp2ManageNameIDRequest_Consent_set(swigCPtr, value);
  }

  public String getConsent() {
    return lassoJNI.Samlp2ManageNameIDRequest_Consent_get(swigCPtr);
  }

  public Samlp2ManageNameIDRequest() {
    this(lassoJNI.new_Samlp2ManageNameIDRequest(), true);
  }

  public String dump() {
    return lassoJNI.Samlp2ManageNameIDRequest_dump(swigCPtr);
  }

}
