/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2BaseIDAbstract extends Node {
  protected Saml2BaseIDAbstract(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2BaseIDAbstract obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setNameQualifier(String value) {
    lassoJNI.Saml2BaseIDAbstract_nameQualifier_set(swigCPtr, this, value);
  }

  public String getNameQualifier() {
    return lassoJNI.Saml2BaseIDAbstract_nameQualifier_get(swigCPtr, this);
  }

  public void setSpNameQualifier(String value) {
    lassoJNI.Saml2BaseIDAbstract_spNameQualifier_set(swigCPtr, this, value);
  }

  public String getSpNameQualifier() {
    return lassoJNI.Saml2BaseIDAbstract_spNameQualifier_get(swigCPtr, this);
  }

  public Saml2BaseIDAbstract() {
    this(lassoJNI.new_Saml2BaseIDAbstract(), true);
  }

  public String dump() {
    return lassoJNI.Saml2BaseIDAbstract_dump(swigCPtr, this);
  }

}
