/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlAudienceRestrictionCondition extends SamlConditionAbstract {
  protected SamlAudienceRestrictionCondition(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlAudienceRestrictionCondition obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAudience(StringList audience) {
    lassoJNI.set_SamlAudienceRestrictionCondition_audience(swigCPtr, StringList.getCPtr(audience));
  }

  public StringList getAudience() {
    long cPtr = lassoJNI.get_SamlAudienceRestrictionCondition_audience(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public SamlAudienceRestrictionCondition() {
    this(lassoJNI.new_SamlAudienceRestrictionCondition(), true);
  }

  public String dump() {
    return lassoJNI.SamlAudienceRestrictionCondition_dump(swigCPtr);
  }

}
