/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2StatementAbstract extends Node {
  protected Saml2StatementAbstract(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2StatementAbstract obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public Saml2StatementAbstract() {
    this(lassoJNI.new_Saml2StatementAbstract(), true);
  }

  public String dump() {
    return lassoJNI.Saml2StatementAbstract_dump(swigCPtr, this);
  }

}
