/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlAttributeDesignator extends Node {
  protected SamlAttributeDesignator(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlAttributeDesignator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAttributeName(String AttributeName) {
    lassoJNI.set_SamlAttributeDesignator_attributeName(swigCPtr, AttributeName);
  }

  public String getAttributeName() {
    return lassoJNI.get_SamlAttributeDesignator_attributeName(swigCPtr);
  }

  public void setAttributeNamespace(String AttributeNamespace) {
    lassoJNI.set_SamlAttributeDesignator_attributeNamespace(swigCPtr, AttributeNamespace);
  }

  public String getAttributeNamespace() {
    return lassoJNI.get_SamlAttributeDesignator_attributeNamespace(swigCPtr);
  }

  public SamlAttributeDesignator() {
    this(lassoJNI.new_SamlAttributeDesignator(), true);
  }

  public String dump() {
    return lassoJNI.SamlAttributeDesignator_dump(swigCPtr);
  }

}
