/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Samlp2StatusResponse extends Node {
  protected Samlp2StatusResponse(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Samlp2StatusResponse obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setID(String value) {
    lassoJNI.Samlp2StatusResponse_ID_set(swigCPtr, value);
  }

  public String getID() {
    return lassoJNI.Samlp2StatusResponse_ID_get(swigCPtr);
  }

  public void setInResponseTo(String value) {
    lassoJNI.Samlp2StatusResponse_inResponseTo_set(swigCPtr, value);
  }

  public String getInResponseTo() {
    return lassoJNI.Samlp2StatusResponse_inResponseTo_get(swigCPtr);
  }

  public void setVersion(String value) {
    lassoJNI.Samlp2StatusResponse_Version_set(swigCPtr, value);
  }

  public String getVersion() {
    return lassoJNI.Samlp2StatusResponse_Version_get(swigCPtr);
  }

  public void setIssueInstant(String value) {
    lassoJNI.Samlp2StatusResponse_issueInstant_set(swigCPtr, value);
  }

  public String getIssueInstant() {
    return lassoJNI.Samlp2StatusResponse_issueInstant_get(swigCPtr);
  }

  public void setDestination(String value) {
    lassoJNI.Samlp2StatusResponse_Destination_set(swigCPtr, value);
  }

  public String getDestination() {
    return lassoJNI.Samlp2StatusResponse_Destination_get(swigCPtr);
  }

  public void setConsent(String value) {
    lassoJNI.Samlp2StatusResponse_Consent_set(swigCPtr, value);
  }

  public String getConsent() {
    return lassoJNI.Samlp2StatusResponse_Consent_get(swigCPtr);
  }

  public void setIssuer(Saml2NameID value) {
    lassoJNI.Samlp2StatusResponse_issuer_set(swigCPtr, Saml2NameID.getCPtr(value));
  }

  public Saml2NameID getIssuer() {
    long cPtr = lassoJNI.Samlp2StatusResponse_issuer_get(swigCPtr);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setExtensions(Samlp2Extensions value) {
    lassoJNI.Samlp2StatusResponse_extensions_set(swigCPtr, Samlp2Extensions.getCPtr(value));
  }

  public Samlp2Extensions getExtensions() {
    long cPtr = lassoJNI.Samlp2StatusResponse_extensions_get(swigCPtr);
    return (cPtr == 0) ? null : new Samlp2Extensions(cPtr, false);
  }

  public void setStatus(Samlp2Status value) {
    lassoJNI.Samlp2StatusResponse_status_set(swigCPtr, Samlp2Status.getCPtr(value));
  }

  public Samlp2Status getStatus() {
    long cPtr = lassoJNI.Samlp2StatusResponse_status_get(swigCPtr);
    return (cPtr == 0) ? null : new Samlp2Status(cPtr, false);
  }

  public Samlp2StatusResponse() {
    this(lassoJNI.new_Samlp2StatusResponse(), true);
  }

  public String dump() {
    return lassoJNI.Samlp2StatusResponse_dump(swigCPtr);
  }

}
