/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2Action extends Node {
  protected Saml2Action(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2Action obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setContent(String value) {
    lassoJNI.Saml2Action_content_set(swigCPtr, this, value);
  }

  public String getContent() {
    return lassoJNI.Saml2Action_content_get(swigCPtr, this);
  }

  public void setNamespace(String value) {
    lassoJNI.Saml2Action_namespace_set(swigCPtr, this, value);
  }

  public String getNamespace() {
    return lassoJNI.Saml2Action_namespace_get(swigCPtr, this);
  }

  public Saml2Action() {
    this(lassoJNI.new_Saml2Action(), true);
  }

  public String dump() {
    return lassoJNI.Saml2Action_dump(swigCPtr, this);
  }

}
