/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2AuthnContext extends Node {
  protected Saml2AuthnContext(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2AuthnContext obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAuthnContextClassRef(String value) {
    lassoJNI.Saml2AuthnContext_authnContextClassRef_set(swigCPtr, this, value);
  }

  public String getAuthnContextClassRef() {
    return lassoJNI.Saml2AuthnContext_authnContextClassRef_get(swigCPtr, this);
  }

  public void setAuthnContextDeclRef(String value) {
    lassoJNI.Saml2AuthnContext_authnContextDeclRef_set(swigCPtr, this, value);
  }

  public String getAuthnContextDeclRef() {
    return lassoJNI.Saml2AuthnContext_authnContextDeclRef_get(swigCPtr, this);
  }

  public void setAuthenticatingAuthority(String value) {
    lassoJNI.Saml2AuthnContext_AuthenticatingAuthority_set(swigCPtr, this, value);
  }

  public String getAuthenticatingAuthority() {
    return lassoJNI.Saml2AuthnContext_AuthenticatingAuthority_get(swigCPtr, this);
  }

  public Saml2AuthnContext() {
    this(lassoJNI.new_Saml2AuthnContext(), true);
  }

  public String dump() {
    return lassoJNI.Saml2AuthnContext_dump(swigCPtr, this);
  }

}
