/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2AttributeStatement extends Saml2StatementAbstract {
  protected Saml2AttributeStatement(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2AttributeStatement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAttribute(NodeList value) {
    lassoJNI.Saml2AttributeStatement_attribute_set(swigCPtr, this, NodeList.getCPtr(value), value);
  }

  public NodeList getAttribute() {
    long cPtr = lassoJNI.Saml2AttributeStatement_attribute_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NodeList(cPtr, false);
  }

  public void setEncryptedAttribute(NodeList value) {
    lassoJNI.Saml2AttributeStatement_encryptedAttribute_set(swigCPtr, this, NodeList.getCPtr(value), value);
  }

  public NodeList getEncryptedAttribute() {
    long cPtr = lassoJNI.Saml2AttributeStatement_encryptedAttribute_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NodeList(cPtr, false);
  }

  public Saml2AttributeStatement() {
    this(lassoJNI.new_Saml2AttributeStatement(), true);
  }

  public String dump() {
    return lassoJNI.Saml2AttributeStatement_dump(swigCPtr, this);
  }

}
