/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2Conditions extends Node {
  protected Saml2Conditions(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2Conditions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setNotBefore(String value) {
    lassoJNI.Saml2Conditions_notBefore_set(swigCPtr, this, value);
  }

  public String getNotBefore() {
    return lassoJNI.Saml2Conditions_notBefore_get(swigCPtr, this);
  }

  public void setNotOnOrAfter(String value) {
    lassoJNI.Saml2Conditions_notOnOrAfter_set(swigCPtr, this, value);
  }

  public String getNotOnOrAfter() {
    return lassoJNI.Saml2Conditions_notOnOrAfter_get(swigCPtr, this);
  }

  public void setCondition(NodeList value) {
    lassoJNI.Saml2Conditions_condition_set(swigCPtr, this, NodeList.getCPtr(value), value);
  }

  public NodeList getCondition() {
    long cPtr = lassoJNI.Saml2Conditions_condition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NodeList(cPtr, false);
  }

  public void setAudienceRestriction(NodeList value) {
    lassoJNI.Saml2Conditions_audienceRestriction_set(swigCPtr, this, NodeList.getCPtr(value), value);
  }

  public NodeList getAudienceRestriction() {
    long cPtr = lassoJNI.Saml2Conditions_audienceRestriction_get(swigCPtr, this);
    return (cPtr == 0) ? null : new NodeList(cPtr, false);
  }

  public Saml2Conditions() {
    this(lassoJNI.new_Saml2Conditions(), true);
  }

  public String dump() {
    return lassoJNI.Saml2Conditions_dump(swigCPtr, this);
  }

}
