/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.28
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2SubjectLocality extends Node {
  protected Saml2SubjectLocality(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2SubjectLocality obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAddress(String value) {
    lassoJNI.Saml2SubjectLocality_Address_set(swigCPtr, value);
  }

  public String getAddress() {
    return lassoJNI.Saml2SubjectLocality_Address_get(swigCPtr);
  }

  public void setDNSName(String value) {
    lassoJNI.Saml2SubjectLocality_DNSName_set(swigCPtr, value);
  }

  public String getDNSName() {
    return lassoJNI.Saml2SubjectLocality_DNSName_get(swigCPtr);
  }

  public Saml2SubjectLocality() {
    this(lassoJNI.new_Saml2SubjectLocality(), true);
  }

  public String dump() {
    return lassoJNI.Saml2SubjectLocality_dump(swigCPtr);
  }

}
