/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlSubjectStatement extends SamlSubjectStatementAbstract {
  protected SamlSubjectStatement(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlSubjectStatement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setSubject(SamlSubject value) {
    lassoJNI.SamlSubjectStatement_subject_set(swigCPtr, this, SamlSubject.getCPtr(value), value);
  }

  public SamlSubject getSubject() {
    long cPtr = lassoJNI.SamlSubjectStatement_subject_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SamlSubject(cPtr, false);
  }

  public SamlSubjectStatement() {
    this(lassoJNI.new_SamlSubjectStatement(), true);
  }

  public String dump() {
    return lassoJNI.SamlSubjectStatement_dump(swigCPtr, this);
  }

}
