/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2Subject extends Node {
  protected Saml2Subject(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2Subject obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setBaseID(Saml2BaseIDAbstract value) {
    lassoJNI.Saml2Subject_baseID_set(swigCPtr, this, Saml2BaseIDAbstract.getCPtr(value), value);
  }

  public Saml2BaseIDAbstract getBaseID() {
    long cPtr = lassoJNI.Saml2Subject_baseID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2BaseIDAbstract(cPtr, false);
  }

  public void setNameID(Saml2NameID value) {
    lassoJNI.Saml2Subject_nameID_set(swigCPtr, this, Saml2NameID.getCPtr(value), value);
  }

  public Saml2NameID getNameID() {
    long cPtr = lassoJNI.Saml2Subject_nameID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2NameID(cPtr, false);
  }

  public void setEncryptedID(Saml2EncryptedElement value) {
    lassoJNI.Saml2Subject_encryptedID_set(swigCPtr, this, Saml2EncryptedElement.getCPtr(value), value);
  }

  public Saml2EncryptedElement getEncryptedID() {
    long cPtr = lassoJNI.Saml2Subject_encryptedID_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2EncryptedElement(cPtr, false);
  }

  public void setSubjectConfirmation(Saml2SubjectConfirmation value) {
    lassoJNI.Saml2Subject_subjectConfirmation_set(swigCPtr, this, Saml2SubjectConfirmation.getCPtr(value), value);
  }

  public Saml2SubjectConfirmation getSubjectConfirmation() {
    long cPtr = lassoJNI.Saml2Subject_subjectConfirmation_get(swigCPtr, this);
    return (cPtr == 0) ? null : new Saml2SubjectConfirmation(cPtr, false);
  }

  public Saml2Subject() {
    this(lassoJNI.new_Saml2Subject(), true);
  }

  public String dump() {
    return lassoJNI.Saml2Subject_dump(swigCPtr, this);
  }

}
