/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class SamlAttributeDesignator extends Node {
  protected SamlAttributeDesignator(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(SamlAttributeDesignator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setAttributeName(String value) {
    lassoJNI.SamlAttributeDesignator_attributeName_set(swigCPtr, this, value);
  }

  public String getAttributeName() {
    return lassoJNI.SamlAttributeDesignator_attributeName_get(swigCPtr, this);
  }

  public void setAttributeNamespace(String value) {
    lassoJNI.SamlAttributeDesignator_attributeNamespace_set(swigCPtr, this, value);
  }

  public String getAttributeNamespace() {
    return lassoJNI.SamlAttributeDesignator_attributeNamespace_get(swigCPtr, this);
  }

  public SamlAttributeDesignator() {
    this(lassoJNI.new_SamlAttributeDesignator(), true);
  }

  public String dump() {
    return lassoJNI.SamlAttributeDesignator_dump(swigCPtr, this);
  }

}
