/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.31
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Saml2Attribute extends Node {
  protected Saml2Attribute(long cPtr, boolean cMemoryOwn) {
    super(cPtr, cMemoryOwn);
  }

  protected static long getCPtr(Saml2Attribute obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
  super.delete();
}

  public void setName(String value) {
    lassoJNI.Saml2Attribute_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return lassoJNI.Saml2Attribute_name_get(swigCPtr, this);
  }

  public void setNameFormat(String value) {
    lassoJNI.Saml2Attribute_nameFormat_set(swigCPtr, this, value);
  }

  public String getNameFormat() {
    return lassoJNI.Saml2Attribute_nameFormat_get(swigCPtr, this);
  }

  public void setFriendlyName(String value) {
    lassoJNI.Saml2Attribute_friendlyName_set(swigCPtr, this, value);
  }

  public String getFriendlyName() {
    return lassoJNI.Saml2Attribute_friendlyName_get(swigCPtr, this);
  }

  public Saml2Attribute() {
    this(lassoJNI.new_Saml2Attribute(), true);
  }

  public String dump() {
    return lassoJNI.Saml2Attribute_dump(swigCPtr, this);
  }

}
