/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.24
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;

public class Server {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Server(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Server obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected Server() {
    this(0, false);
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lassoJNI.delete_Server(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setCertificate(String certificate) {
    lassoJNI.set_Server_certificate(swigCPtr, certificate);
  }

  public String getCertificate() {
    return lassoJNI.get_Server_certificate(swigCPtr);
  }

  public void setPrivateKey(String private_key) {
    lassoJNI.set_Server_privateKey(swigCPtr, private_key);
  }

  public String getPrivateKey() {
    return lassoJNI.get_Server_privateKey(swigCPtr);
  }

  public void setPrivateKeyPassword(String private_key_password) {
    lassoJNI.set_Server_privateKeyPassword(swigCPtr, private_key_password);
  }

  public String getPrivateKeyPassword() {
    return lassoJNI.get_Server_privateKeyPassword(swigCPtr);
  }

  public void setSignatureMethod(int signature_method) {
    lassoJNI.set_Server_signatureMethod(swigCPtr, signature_method);
  }

  public int getSignatureMethod() {
    return lassoJNI.get_Server_signatureMethod(swigCPtr);
  }

  public void setCaCertChain(String ca_cert_chain) {
    lassoJNI.set_Server_caCertChain(swigCPtr, ca_cert_chain);
  }

  public String getCaCertChain() {
    return lassoJNI.get_Server_caCertChain(swigCPtr);
  }

  public void setMetadataFilename(String metadata_filename) {
    lassoJNI.set_Server_metadataFilename(swigCPtr, metadata_filename);
  }

  public String getMetadataFilename() {
    return lassoJNI.get_Server_metadataFilename(swigCPtr);
  }

  public void setProviderId(String ProviderID) {
    lassoJNI.set_Server_providerId(swigCPtr, ProviderID);
  }

  public String getProviderId() {
    return lassoJNI.get_Server_providerId(swigCPtr);
  }

  public void setPublicKey(String public_key) {
    lassoJNI.set_Server_publicKey(swigCPtr, public_key);
  }

  public String getPublicKey() {
    return lassoJNI.get_Server_publicKey(swigCPtr);
  }

  public void setRole(int role) {
    lassoJNI.set_Server_role(swigCPtr, role);
  }

  public int getRole() {
    return lassoJNI.get_Server_role(swigCPtr);
  }

  public StringList getProviderIds() {
    long cPtr = lassoJNI.get_Server_providerIds(swigCPtr);
    return (cPtr == 0) ? null : new StringList(cPtr, false);
  }

  public Server(String metadata, String privateKey, String privateKeyPassword, String certificate) {
    this(lassoJNI.new_Server(metadata, privateKey, privateKeyPassword, certificate), true);
  }

  public static Server newFromDump(String dump) {
    long cPtr = lassoJNI.Server_newFromDump(dump);
    return (cPtr == 0) ? null : new Server(cPtr, true);
  }

  public boolean acceptHttpMethod(Provider remote_provider, SWIGTYPE_p_LassoMdProtocolType protocol_type, int http_method, boolean initiate_profile) {
    return lassoJNI.Server_acceptHttpMethod(swigCPtr, Provider.getCPtr(remote_provider), SWIGTYPE_p_LassoMdProtocolType.getCPtr(protocol_type), http_method, initiate_profile);
  }

  public String getAssertionConsumerServiceUrl(String service_id) {
    return lassoJNI.Server_getAssertionConsumerServiceUrl(swigCPtr, service_id);
  }

  public String getBase64SuccinctId() {
    return lassoJNI.Server_getBase64SuccinctId(swigCPtr);
  }

  public String getOrganization() {
    return lassoJNI.Server_getOrganization(swigCPtr);
  }

  public int getFirstHttpMethod(Provider remote_provider, SWIGTYPE_p_LassoMdProtocolType protocol_type) {
    return lassoJNI.Server_getFirstHttpMethod(swigCPtr, Provider.getCPtr(remote_provider), SWIGTYPE_p_LassoMdProtocolType.getCPtr(protocol_type));
  }

  public String getMetadataOne(String name) {
    return lassoJNI.Server_getMetadataOne(swigCPtr, name);
  }

  public boolean hasProtocolProfile(SWIGTYPE_p_LassoMdProtocolType protocol_type, String protocol_profile) {
    return lassoJNI.Server_hasProtocolProfile(swigCPtr, SWIGTYPE_p_LassoMdProtocolType.getCPtr(protocol_type), protocol_profile);
  }

  public int addProvider(int role, String metadata, String publicKey, String caCertChain) {
    return lassoJNI.Server_addProvider(swigCPtr, role, metadata, publicKey, caCertChain);
  }

  public String dump() {
    return lassoJNI.Server_dump(swigCPtr);
  }

  public Provider getProvider(String providerId) {
    long cPtr = lassoJNI.Server_getProvider(swigCPtr, providerId);
    return (cPtr == 0) ? null : new Provider(cPtr, false);
  }

}
