/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version: 1.3.21
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.entrouvert.lasso;


public class Session {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected Session(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      lassoJNI.delete_Session(swigCPtr);
    }
    swigCPtr = 0;
  }

  protected static long getCPtr(Session obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public boolean getIsDirty() {
    return lassoJNI.get_Session_isDirty(swigCPtr);
  }

  public Session() {
    this(lassoJNI.new_Session(), true);
  }

  public static Session newFromDump(String dump) {
    long cPtr = lassoJNI.Session_newFromDump(dump);
    return (cPtr == 0) ? null : new Session(cPtr, true);
  }

  public String dump() {
    return lassoJNI.Session_dump(swigCPtr);
  }

  public String getAuthenticationMethod(String remoteProviderId) {
    return lassoJNI.Session_getAuthenticationMethod(swigCPtr, remoteProviderId);
  }

}
